In [134]:
import pandas as pd
data = pd.read_csv("Clustered_Session.csv")
prod = pd.read_csv("01.Pruduct.csv") #,delimiter = '\t', thousands = ',')

C:\Users\User\anaconda3.7\envs\chaelin_virtenv\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (7) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [136]:
product = prod.drop(['CLNT_ID','HITS_SEQ'],axis = 1)
product[:3]

,SESS_ID,PD_C,PD_ADD_NM,PD_BRA_NM,PD_BUY_AM,PD_BUY_CT
0,7605037,642112,색상:워터멜론,[바비브라운],"39,000",1
1,10189797,570603,색상:BLK0_(BLK0)BLACK|사이즈:120 / 2개,데상트,"39,000",2
2,6158159,179538,(not set),[아베다],"39,000",1

In [148]:
product['PD_BUY_AM'] = product['PD_BUY_AM'].map(lambda x: x.replace(",", ""))

In [149]:
product[:3]

,SESS_ID,PD_C,PD_ADD_NM,PD_BRA_NM,PD_BUY_AM,PD_BUY_CT
0,7605037,642112,색상:워터멜론,[바비브라운],39000,1
1,10189797,570603,색상:BLK0_(BLK0)BLACK|사이즈:120 / 2개,데상트,39000,2
2,6158159,179538,(not set),[아베다],39000,1

In [151]:
#buydata = data.drop(['CLNT_ID','SESS_SEQ','TOT_PAG_VIEW_CT','TOT_SESS_HR_V','CLUSTER'],axis=1)

In [152]:
buydata[:3]

   SESS_ID DVC_CTG_NM      ACTION
0  8641867     mobile  buy,search
1  6616320     mobile  buy,search
2  5886172     mobile  buy,search

In [153]:
df = pd.merge(buydata, product, left_on='SESS_ID', right_on='SESS_ID', how='left')
df[:3]

,SESS_ID,DVC_CTG_NM,ACTION,PD_C,PD_ADD_NM,PD_BRA_NM,PD_BUY_AM,PD_BUY_CT
0,8641867,mobile,"buy,search",370753,색상:선택(04) 기본체크 4번 세트 / 1개,닥스(손수건),20000,1
1,8641867,mobile,"buy,search",370753,색상:선택(09) 81번 세트 / 1개,닥스(손수건),20000,1
2,8641867,mobile,"buy,search",370753,색상:선택(10) 82번 세트 / 1개,닥스(손수건),20000,1

In [154]:
mast = pd.read_csv("06.Master.csv")   #필요없,delimiter = '\t', thousands = ',')

In [155]:
data = pd.merge(mast, df, left_on='PD_C', right_on='PD_C', how='left')
data.shape

(6158109, 12)

In [156]:
#ddata = data.drop(['CLAC2_NM','SESS'], axis=1)
data[:1]

,PD_C,PD_NM,CLAC1_NM,CLAC2_NM,CLAC3_NM,SESS_ID,DVC_CTG_NM,ACTION,PD_ADD_NM,PD_BRA_NM,PD_BUY_AM,PD_BUY_CT
0,64382,언더아머 남성 UA HG 아머 모크 LS 1289559-001 - 블랙 / MD[95],스포츠패션,남성일반스포츠의류,남성스포츠티셔츠,2330751.0,mobile,"buy,search",색상:블랙|사이즈:MD[95] / 1개,언더아머(스포츠),49000,1

In [127]:
data.isnull().sum()

PD_C            0
PD_NM           0
CLAC1_NM        0
CLAC2_NM        0
CLAC3_NM        0
SESS_ID       292
DVC_CTG_NM    292
ACTION        292
PD_ADD_NM     292
PD_BRA_NM     292
PD_BUY_AM     292
PD_BUY_CT     292
dtype: int64

In [157]:
data = data.dropna()
data.isnull().sum()

PD_C          0
PD_NM         0
CLAC1_NM      0
CLAC2_NM      0
CLAC3_NM      0
SESS_ID       0
DVC_CTG_NM    0
ACTION        0
PD_ADD_NM     0
PD_BRA_NM     0
PD_BUY_AM     0
PD_BUY_CT     0
dtype: int64

In [158]:
data.shape

(6157817, 12)

In [159]:
data.dtypes

PD_C            int64
PD_NM          object
CLAC1_NM       object
CLAC2_NM       object
CLAC3_NM       object
SESS_ID       float64
DVC_CTG_NM     object
ACTION         object
PD_ADD_NM      object
PD_BRA_NM      object
PD_BUY_AM      object
PD_BUY_CT      object
dtype: object

In [163]:
#data = data.astype({'PD_BUY_CT':'float'})
data.isnull().sum()

PD_C          0
PD_NM         0
CLAC1_NM      0
CLAC2_NM      0
CLAC3_NM      0
SESS_ID       0
DVC_CTG_NM    0
ACTION        0
PD_ADD_NM     0
PD_BRA_NM     0
PD_BUY_AM     0
PD_BUY_CT     0
dtype: int64

In [115]:
data.shape

(6157817, 12)

In [206]:
check = data['PD_C'] == 248086
data[check][40:50]

,PD_C,PD_NM,CLAC1_NM,CLAC2_NM,CLAC3_NM,SESS_ID,DVC_CTG_NM,ACTION,PD_ADD_NM,PD_BRA_NM,PD_BUY_AM,PD_BUY_CT,rank1
2827265,248086,[6상품권]자음 기초2종 기획세트 - 세트,화장품/뷰티케어,스킨케어,스킨케어세트,7600508.0,mobile,"buy,search",타입:세트 / 1개,설화수,120000,1,NaN
2827266,248086,[6상품권]자음 기초2종 기획세트 - 세트,화장품/뷰티케어,스킨케어,스킨케어세트,7597691.0,mobile,"buy,search",타입:세트 / 1개,설화수,120000,1,NaN
2827267,248086,[6상품권]자음 기초2종 기획세트 - 세트,화장품/뷰티케어,스킨케어,스킨케어세트,7537432.0,mobile,"buy,search",타입:세트 / 1개,설화수,120000,1,NaN
2827268,248086,[6상품권]자음 기초2종 기획세트 - 세트,화장품/뷰티케어,스킨케어,스킨케어세트,8056339.0,desktop,"buy,search",타입:세트,[설화수],120000,1,NaN
2827269,248086,[6상품권]자음 기초2종 기획세트 - 세트,화장품/뷰티케어,스킨케어,스킨케어세트,7574721.0,mobile,"buy,search",타입:세트 / 1개,설화수,120000,1,NaN
2827270,248086,[6상품권]자음 기초2종 기획세트 - 세트,화장품/뷰티케어,스킨케어,스킨케어세트,7897617.0,mobile,buy,타입:세트 / 1개,설화수,120000,1,NaN
2827271,248086,[6상품권]자음 기초2종 기획세트 - 세트,화장품/뷰티케어,스킨케어,스킨케어세트,8101814.0,mobile,"buy,search",타입:세트 / 1개,설화수,120000,1,NaN
2827272,248086,[6상품권]자음 기초2종 기획세트 - 세트,화장품/뷰티케어,스킨케어,스킨케어세트,7580324.0,tablet,"buy,search",타입:세트 / 1개,설화수,120000,1,NaN
2827273,248086,[6상품권]자음 기초2종 기획세트 - 세트,화장품/뷰티케어,스킨케어,스킨케어세트,7491754.0,mobile,buy,타입:세트 / 1개,설화수,120000,1,NaN
2827274,248086,[6상품권]자음 기초2종 기획세트 - 세트,화장품/뷰티케어,스킨케어,스킨케어세트,8090219.0,mobile,"buy,search",타입:세트 / 1개,설화수,120000,1,NaN

In [212]:
fun = data['PD_BUY_CT'] == 200
data[fun]
#data[fun].shape

,PD_C,PD_NM,CLAC1_NM,CLAC2_NM,CLAC3_NM,SESS_ID,DVC_CTG_NM,ACTION,PD_ADD_NM,PD_BRA_NM,PD_BUY_AM,PD_BUY_CT,rank1
1389771,365082,SUNRAY ADJUST 4 BGP 386518-011 - 180,스포츠패션,유아동스포츠화,유아동스포츠샌들/슬리퍼,6078738.0,desktop,buy,사이즈:240,[나이키 키즈],39200,200,NaN
2559367,744058,스누피 라인34 - 랜덤,청소/세탁/욕실용품,욕실용품,수건,5396289.0,mobile,"buy,search",색상:아이보리 / 200개,송월타올,1700,200,NaN
2633631,674046,남성 순면 반팔런닝 1매 - 105,속옷/양말/홈웨어,남성속옷,남성런닝셔츠,3150358.0,mobile,buy,사이즈:110 / 200개,돈앤돈스,1950,200,NaN
2795981,211134,LED 2WAY 캠핑등 KMA14A32 - 오렌지 / FREE,아웃도어/레저,등산,기타등산용품,7319580.0,desktop,buy,색상:오렌지/사이즈:FREE,[케이투],15000,200,NaN
4234096,281787,[기프팅] 투썸이중텀블러300(레드),상품권,모바일상품권,식음료모바일상품권,8501986.0,mobile,buy,200개,투썸플레이스,1600,200,NaN
4448191,168942,페스티발 백 트레포일 (BK6730) - 000,스포츠패션,스포츠잡화,스포츠가방,3279792.0,mobile,"buy,search",사이즈:000 / 200개,아디다스 오리지널,25000,200,NaN
5164941,771600,기능성브라탑_bratop_random - 그레이 / 88,여성의류,여성의류상의,여성티셔츠/탑,9383039.0,desktop,buy,색상:퍼플/사이즈:66,[쿠기],1000,200,NaN
5164942,771600,기능성브라탑_bratop_random - 그레이 / 88,여성의류,여성의류상의,여성티셔츠/탑,9383039.0,desktop,buy,색상:레오파드/사이즈:66,[쿠기],1000,200,NaN
5164949,771600,기능성브라탑_bratop_random - 그레이 / 88,여성의류,여성의류상의,여성티셔츠/탑,5757027.0,desktop,buy,색상:그레이/사이즈:88,[쿠기],1000,200,NaN
5164950,771600,기능성브라탑_bratop_random - 그레이 / 88,여성의류,여성의류상의,여성티셔츠/탑,9383039.0,desktop,buy,색상:퍼플/사이즈:66,[쿠기],1000,200,NaN
5164951,771600,기능성브라탑_bratop_random - 그레이 / 88,여성의류,여성의류상의,여성티셔츠/탑,9383039.0,desktop,buy,색상:레오파드/사이즈:66,[쿠기],1000,200,NaN
5164957,771600,기능성브라탑_bratop_random - 그레이 / 88,여성의류,여성의류상의,여성티셔츠/탑,9383518.0,desktop,buy,색상:그레이/사이즈:77,[쿠기],1000,200,NaN

In [175]:
data['rank1'] = data['PD_BUY_CT'].rank(method='min', ascending=False)

In [176]:
data

,PD_C,PD_NM,CLAC1_NM,CLAC2_NM,CLAC3_NM,SESS_ID,DVC_CTG_NM,ACTION,PD_ADD_NM,PD_BRA_NM,PD_BUY_AM,PD_BUY_CT,rank1
0,64382,언더아머 남성 UA HG 아머 모크 LS 1289559-001 - 블랙 / MD[95],스포츠패션,남성일반스포츠의류,남성스포츠티셔츠,2330751.0,mobile,"buy,search",색상:블랙|사이즈:MD[95] / 1개,언더아머(스포츠),49000,1,NaN
1,64382,언더아머 남성 UA HG 아머 모크 LS 1289559-001 - 블랙 / MD[95],스포츠패션,남성일반스포츠의류,남성스포츠티셔츠,2330751.0,desktop,"buy,search",색상:블랙|사이즈:MD[95] / 1개,언더아머(스포츠),49000,1,NaN
2,64382,언더아머 남성 UA HG 아머 모크 LS 1289559-001 - 블랙 / MD[95],스포츠패션,남성일반스포츠의류,남성스포츠티셔츠,2330751.0,mobile,"buy,search",색상:블랙|사이즈:MD[95] / 1개,언더아머(스포츠),49000,1,NaN
3,64382,언더아머 남성 UA HG 아머 모크 LS 1289559-001 - 블랙 / MD[95],스포츠패션,남성일반스포츠의류,남성스포츠티셔츠,2330751.0,mobile,"buy,search",색상:블랙|사이즈:MD[95] / 1개,언더아머(스포츠),49000,1,NaN
4,64382,언더아머 남성 UA HG 아머 모크 LS 1289559-001 - 블랙 / MD[95],스포츠패션,남성일반스포츠의류,남성스포츠티셔츠,2659813.0,mobile,"buy,search",색상:블랙|사이즈:MD[95] / 1개,언더아머(스포츠),49000,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6158104,400197,섀르반 올인원 수영복 (K14D5DM231) - BL/110,시즌스포츠,수영/물놀이,아동수영복,5969955.0,mobile,buy,색상/사이즈:PK/120 / 1개,섀르반,9420,1,NaN
6158105,400197,섀르반 올인원 수영복 (K14D5DM231) - BL/110,시즌스포츠,수영/물놀이,아동수영복,7375797.0,mobile,"buy,search",색상/사이즈:PK/120 / 1개,섀르반,22000,1,NaN
6158106,399225,링클플리츠주름밴딩스커트(CFHM1SK8821) - 블랙 / FREE,여성의류,여성의류하의,여성스커트,3512543.0,desktop,"buy,search",색상:블루/사이즈:FREE,[포커스],19800,1,NaN
6158107,399225,링클플리츠주름밴딩스커트(CFHM1SK8821) - 블랙 / FREE,여성의류,여성의류하의,여성스커트,10190429.0,mobile,"buy,search",색상:핑크|사이즈:FREE / 1개,포커스,19800,1,NaN
6158108,306289,클라이마쿨 쇼츠 [CX3564] - CX3564(그레이) / M,스포츠패션,남성일반스포츠의류,남성일반스포츠바지,8420786.0,mobile,buy,색상:CX3564(그레이)|사이즈:L / 1개,아디다스 오리지날,31200,1,NaN

In [213]:
sess = pd.read_csv("05.Session.csv")
sess[:3]

,CLNT_ID,SESS_ID,SESS_SEQ,SESS_DT,TOT_PAG_VIEW_CT,TOT_SESS_HR_V,DVC_CTG_NM,ZON_NM,CITY_NM
0,5873599,8641867,9,20180509,82.0,"1,890",mobile,Daejeon,Daejeon
1,5873599,6616320,21,20180611,105.0,"1,604",mobile,Busan,Busan
2,5873599,5886172,40,20180624,41.0,632,mobile,Daejeon,Daejeon

In [220]:
dsess = sess.drop(['SESS_DT','SESS_SEQ','TOT_SESS_HR_V','TOT_PAG_VIEW_CT'], axis=1)
dsess[:3]

   CLNT_ID  SESS_ID DVC_CTG_NM   ZON_NM  CITY_NM
0  5873599  8641867     mobile  Daejeon  Daejeon
1  5873599  6616320     mobile    Busan    Busan
2  5873599  5886172     mobile  Daejeon  Daejeon

In [217]:
region = sess.groupby('ZON_NM').agg({'size'})

In [218]:
region

,CLNT_ID,SESS_ID,SESS_SEQ,SESS_DT,TOT_PAG_VIEW_CT,TOT_SESS_HR_V,DVC_CTG_NM,CITY_NM
,size,size,size,size,size,size,size,size
ZON_NM,,,,,,,,
Busan,295940,295940,295940,295940,295940,295940,295940,295940
Chungcheongbuk-do,44455,44455,44455,44455,44455,44455,44455,44455
Chungcheongnam-do,78072,78072,78072,78072,78072,78072,78072,78072
Daegu,116707,116707,116707,116707,116707,116707,116707,116707
Daejeon,60442,60442,60442,60442,60442,60442,60442,60442
Gangwon-do,42701,42701,42701,42701,42701,42701,42701,42701
Gwangju,70773,70773,70773,70773,70773,70773,70773,70773
Gyeonggi-do,469954,469954,469954,469954,469954,469954,469954,469954
Gyeongsangbuk-do,91183,91183,91183,91183,91183,91183,91183,91183
Gyeongsangnam-do,128716,128716,128716,128716,128716,128716,128716,128716
Incheon,100728,100728,100728,100728,100728,100728,100728,100728
Jeju-do,19073,19073,19073,19073,19073,19073,19073,19073
Jeollabuk-do,78437,78437,78437,78437,78437,78437,78437,78437
Jeollanam-do,49299,49299,49299,49299,49299,49299,49299,49299
Seoul,1019843,1019843,1019843,1019843,1019843,1019843,1019843,1019843
Ulsan,46584,46584,46584,46584,46584,46584,46584,46584

In [219]:
product[:3]

,SESS_ID,PD_C,PD_ADD_NM,PD_BRA_NM,PD_BUY_AM,PD_BUY_CT
0,7605037,642112,색상:워터멜론,[바비브라운],39000,1
1,10189797,570603,색상:BLK0_(BLK0)BLACK|사이즈:120 / 2개,데상트,39000,2
2,6158159,179538,(not set),[아베다],39000,1

In [221]:
reproduct = pd.merge(product, dsess, left_on='SESS_ID', right_on='SESS_ID', how='left')

In [222]:
reproduct[:3]

,SESS_ID,PD_C,PD_ADD_NM,PD_BRA_NM,PD_BUY_AM,PD_BUY_CT,CLNT_ID,DVC_CTG_NM,ZON_NM,CITY_NM
0,7605037,642112,색상:워터멜론,[바비브라운],39000,1,4139680,desktop,Seoul,Seoul
1,10189797,570603,색상:BLK0_(BLK0)BLACK|사이즈:120 / 2개,데상트,39000,2,4140076,mobile,Gyeonggi-do,Icheon-si
2,6158159,179538,(not set),[아베다],39000,1,4142395,desktop,Seoul,Seoul

In [224]:
reproduct = reproduct.drop(['CLNT_ID', 'PD_BUY_CT','PD_BUY_AM'], axis=1)
reproduct[:3]

,SESS_ID,PD_C,PD_ADD_NM,PD_BRA_NM,DVC_CTG_NM,ZON_NM,CITY_NM
0,7605037,642112,색상:워터멜론,[바비브라운],desktop,Seoul,Seoul
1,10189797,570603,색상:BLK0_(BLK0)BLACK|사이즈:120 / 2개,데상트,mobile,Gyeonggi-do,Icheon-si
2,6158159,179538,(not set),[아베다],desktop,Seoul,Seoul

In [225]:
regionData = pd.merge(mast, reproduct, left_on='PD_C', right_on='PD_C', how='left')

In [26]:
regionData.isnull().sum()
regionData.shape

(6184014, 12)

In [12]:
#regionData.to_csv('regionData.csv')
import pandas as pd
regionData = pd.read_csv('regionData.csv')

In [14]:
tt = regionData['SESS_ID']==1856814
regionData[tt]

,Unnamed: 0,PD_C,PD_NM,CLAC1_NM,CLAC2_NM,CLAC3_NM,SESS_ID,PD_ADD_NM,PD_BRA_NM,DVC_CTG_NM,ZON_NM,CITY_NM
3992676,3992676,622881,[선미 공항패션]Taylor mini O5NBCB08_PW - BLACK,패션잡화,여성가방,여성토트백,1856814,COLOR:CREAM / 1개,오야니(가방),mobile,Busan,Busan
3992910,3992910,622881,[선미 공항패션]Taylor mini O5NBCB08_PW - BLACK,패션잡화,여성가방,여성토트백,1856814,COLOR:LIP RED / 1개,오야니(가방),mobile,Busan,Busan
3993034,3993034,622881,[선미 공항패션]Taylor mini O5NBCB08_PW - BLACK,패션잡화,여성가방,여성토트백,1856814,COLOR:CREAM / 1개,오야니(가방),mobile,Busan,Busan
3993140,3993140,622881,[선미 공항패션]Taylor mini O5NBCB08_PW - BLACK,패션잡화,여성가방,여성토트백,1856814,COLOR:LIP RED / 1개,오야니(가방),mobile,Busan,Busan
3993211,3993211,622881,[선미 공항패션]Taylor mini O5NBCB08_PW - BLACK,패션잡화,여성가방,여성토트백,1856814,COLOR:PALE BLUE / 1개,오야니(가방),mobile,Busan,Busan
3993212,3993212,622881,[선미 공항패션]Taylor mini O5NBCB08_PW - BLACK,패션잡화,여성가방,여성토트백,1856814,COLOR:CREAM / 1개,오야니(가방),mobile,Busan,Busan
3993344,3993344,622881,[선미 공항패션]Taylor mini O5NBCB08_PW - BLACK,패션잡화,여성가방,여성토트백,1856814,COLOR:LIP RED / 1개,오야니(가방),mobile,Busan,Busan
3993383,3993383,622881,[선미 공항패션]Taylor mini O5NBCB08_PW - BLACK,패션잡화,여성가방,여성토트백,1856814,COLOR:LIP RED / 1개,오야니(가방),mobile,Busan,Busan
3993539,3993539,622881,[선미 공항패션]Taylor mini O5NBCB08_PW - BLACK,패션잡화,여성가방,여성토트백,1856814,COLOR:CREAM / 1개,오야니(가방),mobile,Busan,Busan
3993858,3993858,622881,[선미 공항패션]Taylor mini O5NBCB08_PW - BLACK,패션잡화,여성가방,여성토트백,1856814,COLOR:LIP RED / 1개,오야니(가방),mobile,Busan,Busan
3993859,3993859,622881,[선미 공항패션]Taylor mini O5NBCB08_PW - BLACK,패션잡화,여성가방,여성토트백,1856814,COLOR:LIP RED / 1개,오야니(가방),mobile,Busan,Busan
3994137,3994137,622881,[선미 공항패션]Taylor mini O5NBCB08_PW - BLACK,패션잡화,여성가방,여성토트백,1856814,COLOR:LIP RED / 1개,오야니(가방),mobile,Busan,Busan
3994286,3994286,622881,[선미 공항패션]Taylor mini O5NBCB08_PW - BLACK,패션잡화,여성가방,여성토트백,1856814,COLOR:LIP RED / 1개,오야니(가방),mobile,Busan,Busan
3994358,3994358,622881,[선미 공항패션]Taylor mini O5NBCB08_PW - BLACK,패션잡화,여성가방,여성토트백,1856814,COLOR:PALE BLUE / 1개,오야니(가방),mobile,Busan,Busan
3994618,3994618,622881,[선미 공항패션]Taylor mini O5NBCB08_PW - BLACK,패션잡화,여성가방,여성토트백,1856814,COLOR:LIP RED / 1개,오야니(가방),mobile,Busan,Busan
3994619,3994619,622881,[선미 공항패션]Taylor mini O5NBCB08_PW - BLACK,패션잡화,여성가방,여성토트백,1856814,COLOR:LEMON / 1개,오야니(가방),mobile,Busan,Busan
3994620,3994620,622881,[선미 공항패션]Taylor mini O5NBCB08_PW - BLACK,패션잡화,여성가방,여성토트백,1856814,COLOR:LEMON / 1개,오야니(가방),mobile,Busan,Busan
3994741,3994741,622881,[선미 공항패션]Taylor mini O5NBCB08_PW - BLACK,패션잡화,여성가방,여성토트백,1856814,COLOR:LIP RED / 1개,오야니(가방),mobile,Busan,Busan
3994742,3994742,622881,[선미 공항패션]Taylor mini O5NBCB08_PW - BLACK,패션잡화,여성가방,여성토트백,1856814,COLOR:LIP RED / 1개,오야니(가방),mobile,Busan,Busan
3994997,3994997,622881,[선미 공항패션]Taylor mini O5NBCB08_PW - BLACK,패션잡화,여성가방,여성토트백,1856814,COLOR:CREAM / 1개,오야니(가방),mobile,Busan,Busan
3995146,3995146,622881,[선미 공항패션]Taylor mini O5NBCB08_PW - BLACK,패션잡화,여성가방,여성토트백,1856814,COLOR:CREAM / 1개,오야니(가방),mobile,Busan,Busan
3995147,3995147,622881,[선미 공항패션]Taylor mini O5NBCB08_PW - BLACK,패션잡화,여성가방,여성토트백,1856814,COLOR:LIP RED / 1개,오야니(가방),mobile,Busan,Busan
3995247,3995247,622881,[선미 공항패션]Taylor mini O5NBCB08_PW - BLACK,패션잡화,여성가방,여성토트백,1856814,COLOR:PALE BLUE / 1개,오야니(가방),mobile,Busan,Busan
3995381,3995381,622881,[선미 공항패션]Taylor mini O5NBCB08_PW - BLACK,패션잡화,여성가방,여성토트백,1856814,COLOR:CREAM / 1개,오야니(가방),mobile,Busan,Busan
3995382,3995382,622881,[선미 공항패션]Taylor mini O5NBCB08_PW - BLACK,패션잡화,여성가방,여성토트백,1856814,COLOR:LEMON / 1개,오야니(가방),mobile,Busan,Busan
3995383,3995383,622881,[선미 공항패션]Taylor mini O5NBCB08_PW - BLACK,패션잡화,여성가방,여성토트백,1856814,COLOR:CREAM / 1개,오야니(가방),mobile,Busan,Busan
3995384,3995384,622881,[선미 공항패션]Taylor mini O5NBCB08_PW - BLACK,패션잡화,여성가방,여성토트백,1856814,COLOR:LIP RED / 1개,오야니(가방),mobile,Busan,Busan
3995385,3995385,622881,[선미 공항패션]Taylor mini O5NBCB08_PW - BLACK,패션잡화,여성가방,여성토트백,1856814,COLOR:LIP RED / 1개,오야니(가방),mobile,Busan,Busan
3995386,3995386,622881,[선미 공항패션]Taylor mini O5NBCB08_PW - BLACK,패션잡화,여성가방,여성토트백,1856814,COLOR:LIP RED / 1개,오야니(가방),mobile,Busan,Busan
3995568,3995568,622881,[선미 공항패션]Taylor mini O5NBCB08_PW - BLACK,패션잡화,여성가방,여성토트백,1856814,COLOR:LIP RED / 1개,오야니(가방),mobile,Busan,Busan
3995569,3995569,622881,[선미 공항패션]Taylor mini O5NBCB08_PW - BLACK,패션잡화,여성가방,여성토트백,1856814,COLOR:LIP RED / 1개,오야니(가방),mobile,Busan,Busan
3995570,3995570,622881,[선미 공항패션]Taylor mini O5NBCB08_PW - BLACK,패션잡화,여성가방,여성토트백,1856814,COLOR:CREAM / 1개,오야니(가방),mobile,Busan,Busan
4207907,4207907,624288,(그랑보네르)토트백 (LHFHT111BLLC01),패션잡화,여성가방,여성토트백,1856814,1개,러브캣,mobile,Busan,Busan
4706885,4706885,519715,[COURONNE] Stephanie(스테파니) Shoulder_RXBSX17111...,패션잡화,여성가방,여성숄더백,1856814,사이즈:XXX / 1개,쿠론,mobile,Busan,Busan

In [8]:
seoul_filter = regionData['ZON_NM']=='Seoul'
print(regionData[seoul_filter])

seoul_data = regionData[seoul_filter]
seoul = seoul_data['PD_C']
seoul[:3]

         Unnamed: 0    PD_C  \
0                 0   64382
2                 2   64382
14               14   58280
23               23   58057
28               28  318122
...             ...     ...
6183992     6183992  703105
6183998     6183998  700904
6184007     6184007  400721
6184010     6184010  400197
6184013     6184013  306289

                                                     PD_NM CLAC1_NM  \
0         언더아머 남성 UA HG 아머 모크 LS 1289559-001 - 블랙 / MD[95]    스포츠패션
2         언더아머 남성 UA HG 아머 모크 LS 1289559-001 - 블랙 / MD[95]    스포츠패션
14                      선염스트라이프레이스패치원피스 JROP521D - 블루 / 85     여성의류
23                    배색포인트 랩스타일 원피스 (GIHOP921F) - 화이트 / F     여성의류
28                              H1280YRJ,K,N토트백&크로스백 - 그레이     패션잡화
...                                                    ...      ...
6183992                      여성 샌들 WAD1751GR21 - 네이비 / 225     패션잡화
6183998                                    가우퍼압력솥 6인용(통5중)  식기/조리기구
6184007  [피핀] 클레르 박스 롱티셔츠 103764 - ivory / FREE ◈85564075◈     여성의류
6184010                  섀르반 올인원 수영복 (K14D5DM231) - BL/110    시즌스포츠
6184013                클라이마쿨 쇼츠 [CX3564] - CX3564(그레이) / M    스포츠패션

          CLAC2_NM   CLAC3_NM   SESS_ID                         PD_ADD_NM  \
0        남성일반스포츠의류   남성스포츠티셔츠   2719478             색상:블랙|사이즈:SM[90] / 1개
2        남성일반스포츠의류   남성스포츠티셔츠   2330751             색상:블랙|사이즈:MD[95] / 1개
14          여성의류전신      여성원피스   1145974                 색상:블루|사이즈:85 / 1개
23          여성의류전신      여성원피스   2238421                  색상:블랙|사이즈:F / 1개
28            여성가방      여성토트백   8991846                       색상:그레이 / 1개
...            ...        ...       ...                               ...
6183992        여성화       여성샌들  10613722               색상:네이비|사이즈:230 / 1개
6183998       조리기구        압력솥   8211361                                1개
6184007     여성의류상의    여성티셔츠/탑   2866324  색상:blue|사이즈:FREE ◈85564076◈ / 1개
6184010     수영/물놀이      아동수영복   7375797                색상/사이즈:PK/120 / 1개
6184013  남성일반스포츠의류  남성일반스포츠바지   8420786         색상:CX3564(그레이)|사이즈:L / 1개

          PD_BRA_NM DVC_CTG_NM ZON_NM CITY_NM
0         언더아머(스포츠)     mobile  Seoul   Seoul
2         언더아머(스포츠)     mobile  Seoul   Seoul
14             쥬시쥬디     mobile  Seoul   Seoul
23            지지피엑스     mobile  Seoul   Seoul
28       피에르가르뎅_핸드백    desktop  Seoul   Seoul
...             ...        ...    ...     ...
6183992   랜드로바(여성화)     mobile  Seoul   Seoul
6183998          풍년     mobile  Seoul   Seoul
6184007          피핀     mobile  Seoul   Seoul
6184010         섀르반     mobile  Seoul   Seoul
6184013   아디다스 오리지날     mobile  Seoul   Seoul

[2256541 rows x 12 columns]

0     64382
2     64382
14    58280
Name: PD_C, dtype: int64

In [9]:
cnt = {}

for data in seoul:
    try: cnt[data] +=1
    except: cnt[data] = 1
cnt

{64382: 2,
 58280: 1,
 58057: 1,
 318122: 1,
 318011: 4,
 317956: 5,
 127096: 1,
 125372: 1,
 123395: 1,
 122845: 2,
 210546: 1,
 209216: 5,
 216029: 3,
 214635: 1,
 213856: 1,
 213204: 1,
 213185: 3,
 266015: 2,
 262880: 1,
 180482: 1,
 316577: 4,
 312035: 1,
 311385: 1,
 306459: 1,
 237368: 1,
 236664: 6,
 119241: 2,
 115986: 2,
 115913: 1,
 115120: 1,
 112387: 1,
 111192: 4,
 109817: 2,
 109061: 2,
 24522: 2,
 19895: 1,
 392764: 1,
 392752: 2,
 392707: 2,
 390918: 2,
 390776: 1,
 389861: 1,
 269637: 1,
 263707: 2,
 261189: 3,
 260721: 1,
 342186: 4,
 340646: 4,
 339896: 3,
 337631: 3,
 337277: 3,
 332807: 1,
 439396: 1,
 439375: 1,
 437353: 1,
 455491: 1,
 454332: 3,
 450785: 2,
 445643: 1,
 442458: 1,
 272178: 1,
 271781: 1,
 270447: 1,
 320988: 1,
 320123: 3,
 311334: 1,
 420708: 1,
 416597: 5,
 416457: 4,
 255722: 1,
 255530: 1,
 253913: 2,
 252325: 1,
 387435: 2,
 382813: 2,
 426961: 2,
 223352: 2,
 220679: 1,
 219971: 12,
 247004: 3,
 243270: 3,
 241840: 1,
 411754: 1,
 406760: 5,
 297774: 2,
 295445: 1,
 288446: 56,
 377329: 1,
 375681: 1,
 374527: 1,
 280793: 2,
 280789: 2,
 279605: 1,
 210117: 1,
 208621: 1,
 287895: 3,
 284593: 1,
 280527: 2,
 279374: 1,
 232206: 5,
 371266: 2,
 370639: 12,
 369233: 6,
 365746: 1,
 365623: 2,
 363786: 12,
 283241: 3,
 276527: 1,
 327773: 1,
 324306: 1,
 324198: 1,
 318034: 3,
 194349: 6,
 187980: 1,
 233091: 2,
 229312: 1,
 271794: 1,
 254838: 1,
 250686: 1,
 242172: 2,
 241778: 2,
 360772: 1,
 357272: 1,
 306715: 1,
 302715: 1,
 298644: 1,
 316816: 2,
 292092: 1,
 291572: 1,
 289876: 1,
 217866: 2,
 213980: 2,
 213020: 6,
 330702: 6,
 329568: 1,
 295611: 1,
 290649: 1,
 345706: 1,
 286446: 2,
 207383: 1,
 206078: 1,
 201130: 2,
 199770: 1,
 189844: 10,
 188401: 1,
 312562: 2,
 302676: 1,
 248799: 1,
 268960: 1,
 265299: 1,
 261276: 2,
 260583: 1,
 343155: 2,
 228621: 1,
 227501: 3,
 226742: 1,
 150463: 1,
 186369: 2,
 224334: 1,
 223806: 2,
 220127: 1,
 215831: 1,
 210579: 8,
 243460: 2,
 242764: 1,
 241822: 10,
 241047: 1,
 270134: 1,
 265936: 46,
 265931: 3,
 221068: 1,
 376573: 1,
 327697: 2,
 324074: 2,
 323627: 4,
 311591: 4,
 311166: 1,
 344026: 3,
 340788: 1,
 335404: 34,
 461577: 1,
 459877: 1,
 321568: 1,
 318172: 9,
 317286: 1,
 307656: 1,
 304645: 1,
 304640: 11,
 301168: 1,
 207001: 6,
 371417: 1,
 369613: 4,
 367412: 1,
 305957: 1,
 372406: 1,
 371828: 3,
 368810: 4,
 366811: 2,
 443903: 1,
 251852: 1,
 246366: 1,
 245047: 9,
 244269: 4,
 243593: 4,
 366086: 5,
 362268: 1,
 358822: 2,
 419630: 1,
 417665: 1,
 411767: 1,
 410937: 16,
 410462: 1,
 358244: 1,
 356796: 1,
 478946: 3,
 476244: 1,
 472830: 4,
 407141: 10,
 400426: 1,
 399399: 2,
 276580: 2,
 276496: 2,
 275130: 8,
 275086: 1,
 242039: 3,
 238569: 9,
 234688: 2,
 233262: 1,
 442634: 1,
 438434: 2,
 405434: 2,
 404276: 1,
 403842: 5,
 403576: 1,
 263811: 12,
 259922: 11,
 255399: 1,
 254391: 1,
 428454: 1,
 427874: 7,
 260600: 5,
 259406: 1,
 258614: 2,
 257312: 3,
 330272: 3,
 330102: 1,
 329629: 1,
 247247: 1,
 431712: 2,
 427657: 1,
 425281: 7,
 422482: 1,
 251323: 2,
 116431: 1,
 115441: 5,
 111269: 2,
 421453: 1,
 300580: 1,
 295627: 1,
 295281: 1,
 198298: 3,
 191257: 1,
 188659: 1,
 188584: 2,
 188269: 1,
 186526: 1,
 186349: 1,
 386920: 21,
 382371: 6,
 380108: 1,
 108741: 1,
 170495: 2,
 168494: 1,
 164850: 6,
 316318: 2,
 173921: 6,
 165091: 1,
 396921: 1,
 395781: 2,
 389536: 8,
 384512: 2,
 383016: 2,
 382025: 1,
 346777: 1,
 345800: 1,
 147339: 3,
 143868: 22,
 143580: 1,
 138217: 1,
 137815: 1,
 159057: 1,
 156752: 3,
 256601: 6,
 255329: 3,
 253291: 24,
 156204: 3,
 376700: 2,
 372456: 36,
 371373: 3,
 369656: 2,
 366741: 1,
 380786: 1,
 352385: 1,
 352072: 2,
 119301: 2,
 160295: 12,
 160284: 2,
 154079: 1,
 182642: 1,
 132030: 1,
 127556: 1,
 123908: 2,
 121088: 1,
 157466: 1,
 91461: 1,
 90690: 2,
 90613: 38,
 90225: 1,
 90066: 1,
 89113: 2,
 72472: 1,
 116416: 1,
 114723: 1,
 114286: 1,
 109214: 3,
 70861: 3,
 67399: 1,
 177627: 1,
 176752: 9,
 174399: 2,
 173276: 10,
 173196: 4,
 168507: 1,
 185121: 1,
 183783: 1,
 99526: 1,
 96640: 1,
 85300: 1,
 82553: 1,
 102776: 5,
 102546: 1,
 99632: 1,
 98374: 1,
 97192: 3,
 88705: 1,
 88644: 2,
 61240: 2,
 59392: 19,
 55290: 1,
 52043: 4,
 50698: 2,
 46444: 1,
 180267: 2,
 180048: 1,
 179843: 1,
 179488: 1,
 6637: 1,
 82547: 1,
 84347: 1,
 83483: 1,
 75331: 2,
 65497: 1,
 88240: 1,
 87089: 2,
 104131: 4,
 100696: 3,
 100496: 1,
 97793: 1,
 96861: 1,
 95812: 1,
 23062: 2,
 57799: 2,
 57148: 1,
 55275: 1,
 51296: 1,
 48506: 1,
 44652: 3,
 62351: 1,
 52308: 1,
 42912: 2,
 39598: 1,
 37662: 1,
 13772: 2,
 11268: 1,
 6179: 7,
 2409: 10,
 1370: 15,
 54803: 1,
 49184: 1,
 48364: 1,
 39085: 1,
 80138: 1,
 76450: 3,
 69416: 1,
 67407: 1,
 62870: 1,
 60657: 1,
 28780: 1,
 26742: 1,
 24423: 2,
 21333: 1,
 25734: 9,
 108668: 1,
 104315: 3,
 102099: 1,
 45470: 1,
 43837: 2,
 42444: 1,
 36921: 3,
 34656: 1,
 30183: 2,
 26471: 1,
 100060: 1,
 97017: 2,
 95012: 4,
 93625: 1,
 91078: 1,
 87577: 1,
 87247: 1,
 86406: 2,
 85532: 1,
 984: 1,
 82670: 1,
 82395: 1,
 82300: 1,
 74851: 1,
 19177: 4,
 14071: 4,
 12041: 4,
 11023: 2,
 10394: 1,
 46125: 1,
 42494: 1,
 35844: 4,
 35511: 2,
 35342: 2,
 31218: 9,
 27160: 13,
 26710: 1,
 26414: 17,
 25815: 1,
 24187: 1,
 22655: 14,
 22611: 1,
 22234: 4,
 7884: 31,
 7331: 4,
 62421: 1,
 57457: 2,
 845132: 6,
 835910: 1,
 828922: 1,
 840123: 3,
 834395: 1,
 826914: 1,
 824889: 6,
 6191: 8,
 5313: 9,
 834272: 125,
 831486: 11,
 831254: 1,
 812432: 2,
 812176: 1,
 808131: 1,
 804870: 4,
 816805: 3,
 809737: 3,
 808819: 26,
 801995: 1,
 799606: 2,
 799375: 3,
 796986: 1,
 796450: 38,
 835939: 1,
 843308: 1,
 842954: 1,
 841945: 1,
 793271: 1,
 791653: 5,
 783192: 29,
 781796: 2,
 777132: 1,
 777077: 1,
 820640: 1,
 819820: 2,
 819574: 4,
 817255: 1,
 836798: 1,
 746597: 1,
 745503: 1,
 740425: 4,
 738630: 6,
 814264: 2,
 813214: 1,
 806418: 3,
 804678: 2,
 804053: 1,
 824246: 23,
 729974: 1,
 726801: 1,
 725707: 3,
 778705: 1,
 773345: 1,
 770654: 1,
 769817: 1,
 702021: 3,
 698825: 1,
 689820: 3,
 688366: 1,
 687911: 2,
 685568: 1,
 685318: 1,
 815034: 3,
 800002: 14,
 767837: 2,
 764777: 1,
 787727: 1,
 783865: 1,
 782361: 2,
 666553: 1,
 664561: 1,
 664613: 2,
 657903: 1,
 656590: 4,
 694906: 22,
 687798: 7,
 462408: 1,
 462260: 17,
 342670: 3,
 352313: 1,
 343901: 1,
 337865: 2,
 297371: 1,
 294075: 1,
 283946: 2,
 396278: 3,
 396227: 2,
 393909: 3,
 392486: 4,
 391433: 1,
 390378: 1,
 388341: 1,
 387700: 3,
 386912: 1,
 385081: 6,
 377704: 61,
 457827: 4,
 334072: 1,
 425392: 2,
 420727: 5,
 417001: 1,
 416996: 1,
 416514: 5,
 368334: 1,
 364188: 5,
 363968: 1,
 358998: 8,
 354625: 2,
 354442: 3,
 354151: 1,
 353805: 2,
 308359: 2,
 301298: 10,
 301099: 1,
 297807: 11,
 294051: 5,
 290964: 26,
 265497: 1,
 265189: 1,
 455227: 1,
 452396: 3,
 451912: 1,
 447447: 12,
 446618: 1,
 397686: 1,
 430014: 1,
 424599: 3,
 398161: 1,
 395760: 4,
 394181: 38,
 392146: 1,
 391438: 1,
 384842: 1,
 384837: 3,
 384376: 3,
 441948: 1,
 437471: 1,
 432739: 2,
 431651: 1,
 429406: 1,
 489975: 4,
 489548: 2,
 488441: 2,
 413900: 1,
 412131: 3,
 411425: 28,
 402644: 3,
 402245: 5,
 401297: 1,
 401022: 199,
 401020: 2,
 483458: 1,
 478447: 1,
 477536: 1,
 471000: 1,
 469743: 2,
 469439: 2,
 465126: 9,
 369358: 1,
 368183: 1,
 367959: 5,
 367307: 1,
 365944: 1,
 365417: 4,
 364997: 1,
 359674: 1,
 453440: 4,
 344794: 1,
 339498: 11,
 336443: 1,
 333891: 3,
 413626: 6,
 412143: 1,
 410006: 2,
 406087: 5,
 406021: 3,
 449498: 1,
 449133: 25,
 441783: 2,
 441270: 1,
 440974: 1,
 440903: 3,
 437476: 1,
 436583: 2,
 435459: 5,
 398347: 49,
 399773: 1,
 399382: 9,
 398779: 2,
 329303: 2,
 326858: 1,
 322414: 1,
 393638: 1,
 390035: 14,
 389852: 2,
 382184: 2,
 379810: 2,
 316444: 2,
 315484: 3,
 368515: 9,
 368169: 1,
 365259: 2,
 361689: 1,
 397503: 1,
 393044: 2,
 387544: 5,
 381237: 1,
 380202: 2,
 356246: 1,
 353515: 1,
 353170: 1,
 348161: 2,
 331818: 1,
 329179: 1,
 327411: 4,
 326376: 2,
 324366: 1,
 370167: 7,
 366769: 18,
 364330: 5,
 461116: 2,
 237462: 1,
 237225: 2,
 235301: 2,
 234332: 20,
 160968: 1,
 159448: 3,
 47274: 1,
 40437: 1,
 57820: 1,
 55591: 1,
 186359: 1,
 184534: 5,
 182963: 1,
 181588: 4,
 101128: 5,
 98864: 1,
 95842: 3,
 92901: 1,
 139854: 2,
 138244: 1,
 85665: 1,
 176912: 2,
 172075: 1,
 171600: 1,
 165359: 2,
 165135: 4,
 81052: 1,
 75914: 1,
 68245: 1,
 65578: 1,
 194172: 1,
 193488: 1,
 193028: 2,
 189518: 1,
 155424: 2,
 152811: 1,
 152799: 87,
 151825: 1,
 150788: 1,
 150674: 3,
 150298: 1,
 149949: 1,
 147582: 2,
 145547: 5,
 63553: 1,
 62031: 1,
 178790: 1,
 177482: 1,
 176690: 1,
 228969: 2,
 223684: 1,
 222359: 2,
 217511: 8,
 141327: 2,
 139445: 1,
 199133: 2,
 198469: 1,
 193551: 1,
 191285: 1,
 189880: 3,
 268747: 1,
 268594: 2,
 161494: 1,
 165011: 1,
 164607: 1,
 136351: 2,
 134631: 2,
 130156: 1,
 118995: 1,
 162462: 2,
 177910: 1,
 177376: 1,
 175475: 1,
 171358: 7,
 169693: 16,
 254854: 7,
 253310: 1,
 252209: 2,
 244484: 38,
 244455: 1,
 244190: 1,
 353254: 2,
 350889: 2,
 343797: 4,
 340466: 1,
 424421: 3,
 313494: 4,
 309934: 1,
 307845: 1,
 305070: 2,
 301112: 1,
 296842: 1,
 360759: 1,
 316913: 2,
 316792: 2,
 314864: 3,
 312301: 1,
 312077: 2,
 309453: 2,
 188789: 20,
 187792: 5,
 177038: 4,
 176882: 2,
 175294: 2,
 174487: 3,
 172835: 1,
 172315: 1,
 190274: 2,
 189700: 2,
 424170: 3,
 424091: 2,
 416786: 2,
 416628: 12,
 411561: 8,
 358654: 3,
 358278: 2,
 354683: 3,
 354400: 3,
 304101: 3,
 239071: 5,
 230339: 1,
 225906: 2,
 223372: 1,
 176009: 1,
 171889: 3,
 349235: 1,
 344305: 1,
 335549: 1,
 331285: 3,
 326576: 1,
 407594: 2,
 281281: 1,
 277121: 1,
 270196: 4,
 217696: 12,
 217504: 2,
 217149: 1,
 216286: 2,
 458140: 4,
 457291: 2,
 456577: 4,
 456407: 1,
 454852: 1,
 276812: 15,
 273754: 1,
 272685: 2,
 349644: 8,
 348064: 1,
 346340: 14,
 345397: 4,
 335835: 2,
 331867: 1,
 380105: 2,
 378915: 1,
 374697: 1,
 373209: 3,
 301956: 1,
 301084: 2,
 269681: 2,
 227581: 26,
 222215: 4,
 216103: 1,
 214537: 10,
 201882: 4,
 196476: 8,
 189500: 2,
 187823: 1,
 185218: 1,
 249355: 1,
 432276: 1,
 431682: 1,
 430706: 7,
 427177: 3,
 426317: 3,
 418837: 1,
 356691: 3,
 356484: 2,
 297141: 1,
 294666: 1,
 305180: 2,
 212985: 4,
 210813: 38,
 392142: 5,
 387125: 1,
 383617: 3,
 409443: 2,
 396245: 1,
 386666: 2,
 563681: 1,
 558087: 4,
 549732: 1,
 722916: 1,
 719644: 1,
 541165: 4,
 538509: 6,
 533500: 2,
 526882: 13,
 518558: 2,
 744085: 6,
 743286: 2,
 739065: 6,
 737688: 1,
 737532: 2,
 734373: 1,
 734188: 3,
 729751: 2,
 568154: 1,
 565934: 2,
 788540: 3,
 786933: 1,
 784638: 1,
 780777: 3,
 778861: 9,
 697286: 1,
 716051: 1,
 714811: 6,
 791588: 1,
 790625: 1,
 758480: 1,
 670274: 1,
 627118: 3,
 624368: 1,
 618724: 2,
 618397: 2,
 696737: 1,
 696270: 5,
 694817: 3,
 694506: 3,
 694230: 191,
 689090: 3,
 688811: 3,
 688558: 1,
 688437: 9,
 687410: 9,
 710754: 3,
 666161: 1,
 663110: 1,
 42091: 1,
 37125: 1,
 33773: 1,
 23983: 2,
 98220: 2,
 96124: 5,
 89318: 1,
 80240: 1,
 78382: 1,
 72411: 20,
 64569: 1,
 9116: 1,
 197: 11,
 54117: 1,
 48000: 1,
 46448: 2,
 40867: 1,
 37454: 3,
 34806: 2,
 28164: 1,
 27982: 1,
 26422: 1,
 15885: 7,
 9353: 2,
 7490: 2,
 5693: 1,
 5349: 9,
 4505: 1,
 4457: 97,
 838409: 8,
 829475: 1,
 822904: 85,
 822615: 7,
 842097: 1,
 841647: 16,
 828837: 1,
 828121: 2,
 827904: 2,
 839594: 1,
 837257: 1,
 832577: 9,
 830264: 1,
 814253: 1,
 130295: 1,
 127138: 2,
 126940: 1,
 126380: 1,
 123830: 7,
 813054: 1,
 800343: 2,
 799755: 7,
 809924: 9,
 809034: 27,
 806001: 1,
 804263: 3,
 803903: 8,
 840053: 1,
 834970: 1,
 797669: 1,
 844996: 2,
 844227: 1,
 841659: 1,
 840529: 1,
 832368: 6,
 830500: 2,
 830180: 1,
 826340: 8,
 826315: 15,
 786072: 1,
 783876: 2,
 825164: 1,
 819535: 6,
 816556: 1,
 729672: 6,
 722071: 1,
 756801: 2,
 756318: 2,
 750871: 1,
 775627: 6,
 771384: 1,
 795387: 10,
 779230: 2,
 779019: 2,
 776936: 1,
 748918: 1,
 745253: 11,
 742502: 24,
 738038: 9,
 737895: 1,
 736956: 3,
 736756: 7,
 713062: 4,
 ...}

In [10]:
cnts = sorted(cnt.items(), key = lambda x:x[1], reverse=True)
print(cnts[:10])

[(753343, 4533), (1965, 3704), (748308, 2738), (755981, 2509), (692709, 2224), (718416, 2081), (706924, 1892), (737743, 1850), (658747, 1692), (826313, 1650)]

In [11]:
data1 = regionData[regionData['PD_C'] == 753343 ]
data2 = regionData[regionData['PD_C'] == 1965 ]
data3 = regionData[regionData['PD_C'] == 748308 ]
data4 = regionData[regionData['PD_C'] == 755981 ]
data5 = regionData[regionData['PD_C'] == 692709 ]
data6 = regionData[regionData['PD_C'] == 718416 ]
data7 = regionData[regionData['PD_C'] == 706924 ]
data8 = regionData[regionData['PD_C'] == 737743 ]
data9 = regionData[regionData['PD_C'] == 658747 ]
data10 = regionData[regionData['PD_C'] == 826313 ]


data1 = data1[:1]
data1
data2 = data2[:1]
data3 = data3[:1]
data4 = data4[:1]
data5 = data5[:1]
data6 = data6[:1]
data7 = data7[:1]
data8 = data8[:1]
data9 = data9[:1]
data10 = data10[:1]

## 서울 제품 구매 순위 10

In [12]:
rank = data1
rank = rank.append(data2)
rank = rank.append(data3)
rank = rank.append(data4)
rank = rank.append(data5)
rank = rank.append(data6)
rank = rank.append(data7)
rank = rank.append(data8)
rank = rank.append(data9)
rank = rank.append(data10)
rank

,Unnamed: 0,PD_C,PD_NM,CLAC1_NM,CLAC2_NM,CLAC3_NM,SESS_ID,PD_ADD_NM,PD_BRA_NM,DVC_CTG_NM,ZON_NM,CITY_NM
347613,347613,753343,남성 드로즈 15종 택1 - 06_CCCDRM92WN / 105,속옷/양말/홈웨어,남성속옷,남성팬티,1215019,상품명:06)CDCDRM92NY/사이즈:100,[코데즈컴바인 이너웨어],desktop,Jeollanam-do,Yeosu-si
3288506,3288506,1965,홍삼정 에브리타임(10mlx30포) / 롯데백화점 본점 출고 / 정관장,건강식품,홍삼/인삼가공식품,홍삼액,6195715,1개,정관장,mobile,Gyeonggi-do,Anyang
2871969,2871969,748308,립스틱 - 온 홀드,화장품/뷰티케어,메이크업,립스틱/립라이너,8340830,색상:디바,[맥],desktop,Seoul,Seoul
2515580,2515580,755981,홍삼정진(進) 에브리타임 10mx30포 + 쇼핑백 증정 - 홍삼정진에브리타임,건강식품,홍삼/인삼가공식품,홍삼/인삼혼합세트,906695,선택:홍삼정진에브리타임 / 1개,정관장.,mobile,Seoul,Seoul
838092,838092,692709,에어팟 케이스 고리형 키링 행 - 러블리 핑크,모바일,모바일액세서리,기타모바일액세서리,5350493,색상:러블리 핑크 / 1개,엘라고,mobile,Seoul,Seoul
2852049,2852049,718416,홍삼정 240g 롯데백화점 본점 출고 / 정관장,건강식품,홍삼/인삼가공식품,홍삼액,9047304,1개,정관장,mobile,Jeollabuk-do,Gunsan-si
616126,616126,706924,아몬드브리즈 오리지널 190ml 24팩 - 아몬드 브리즈 오리지널 190mlx24팩,음료,두유,일반두유,9826914,상품명:아몬드 브리즈 오리지널 190mlx24팩 / 1개,매일,mobile,Seoul,Seoul
2918704,2918704,737743,[리필] 르 쿠션 엉크르 드 뽀 SPF23 PA++ 14g - 40,화장품/뷰티케어,메이크업,BB/파운데이션/컴팩트류,9706493,색상:10 / 1개,입생로랑,mobile,Busan,Busan
5789682,5789682,658747,따뚜아쥬 꾸뛰르 타투틴트 - 15바이올렛 컨빅션,화장품/뷰티케어,메이크업,블러셔/쉐이딩/하이라이터,3881549,색상:16누드 엠블럼 / 1개,입생로랑,mobile,Gyeongsangnam-do,Yangsan-si
2115835,2115835,826313,풀무원 생수 2L x 6페트,음료,생수,생수,5101523,1개,웅진식품,mobile,Gwangju,Gwangju

## 경기

In [13]:
gyeonggi_filter = regionData['ZON_NM']=='Gyeonggi-do'
print(regionData[gyeonggi_filter])

gyeonggi_data = regionData[gyeonggi_filter]
gyeonggi = gyeonggi_data['PD_C']
gyeonggi[:1]

         Unnamed: 0    PD_C                                             PD_NM  \
4                 4   64382  언더아머 남성 UA HG 아머 모크 LS 1289559-001 - 블랙 / MD[95]
5                 5   64382  언더아머 남성 UA HG 아머 모크 LS 1289559-001 - 블랙 / MD[95]
7                 7   61729                      88A2933253배트맨스웨트티 - 블랙 / 130
8                 8   61537           닥터마틴 아드리안 블랙, 체리레드 - 02_체리레드 / 250mm(6)
19               19   58098        V넥 고방 체크 롱 원피스 (K65-54615) - 스카이블루(SB) / F
...             ...     ...                                               ...
6183993     6183993  702567                             여성시계 AR11038 파슬코리아 직영
6183994     6183994  702567                             여성시계 AR11038 파슬코리아 직영
6183995     6183995  701213      트렌디한 꽃무늬 오프숄더 롱 원피스 (CVOW72604Q) - 아이보리 / 66
6184004     6184004  405748      폴란드95 구스다운 이불 싱글S.SS 1000 순면 속통 한파용 laselene
6184006     6184006  400890              아디다스 D2M 로고 반팔티셔츠 (BK0937) - 105(XL)

        CLAC1_NM   CLAC2_NM  CLAC3_NM  SESS_ID                  PD_ADD_NM  \
4          스포츠패션  남성일반스포츠의류  남성스포츠티셔츠  2330751      색상:블랙|사이즈:MD[95] / 1개
5          스포츠패션  남성일반스포츠의류  남성스포츠티셔츠  2330751      색상:블랙|사이즈:MD[95] / 1개
7          유아동의류     유아의류상의  영유아티셔츠/탑    68725         색상:블랙|사이즈:140 / 1개
8           패션잡화        남성화      남성부츠  2637569  제품:01_블랙/사이즈(UK):270mm(8)
19          여성의류     여성의류전신     여성원피스  2532908        색상:스카이블루|사이즈:F / 1개
...          ...        ...       ...      ...                        ...
6183993     패션잡화         시계      여성시계   471021                  (not set)
6183994     패션잡화         시계      여성시계   475779                  (not set)
6183995     여성의류     여성의류전신     여성원피스  3584066              색상:네이비/사이즈:55
6184004    침구/수예       성인침구  성인침구속통/솜   183303                         1개
6184006    스포츠패션  남성일반스포츠의류  남성스포츠티셔츠  7091842            사이즈:100(L) / 1개

              PD_BRA_NM DVC_CTG_NM       ZON_NM         CITY_NM
4             언더아머(스포츠)     mobile  Gyeonggi-do        Ansan-si
5             언더아머(스포츠)     mobile  Gyeonggi-do  Gwangmyeong-si
7                 래핑차일드     mobile  Gyeonggi-do       Goyang-si
8                [닥터마틴]    desktop  Gyeonggi-do     Seongnam-si
19                  오조크     mobile  Gyeonggi-do     Seongnam-si
...                 ...        ...          ...             ...
6183993  [엠포리오아르마니(시계)]    desktop  Gyeonggi-do   Pyeongtaek-si
6183994  [엠포리오아르마니(시계)]    desktop  Gyeonggi-do   Pyeongtaek-si
6183995          [클라비스]    desktop  Gyeonggi-do     Hwaseong-si
6184004             라셀렌     mobile  Gyeonggi-do        Suwon-si
6184006        아디다스(의류)     mobile  Gyeonggi-do        Gunpo-si

[1076176 rows x 12 columns]

4    64382
Name: PD_C, dtype: int64

In [14]:
cnt = {}

for data in gyeonggi:
    try: cnt[data] +=1
    except: cnt[data] = 1
cnt

{64382: 2,
 61729: 1,
 61537: 1,
 58098: 1,
 58057: 2,
 56306: 1,
 317956: 1,
 209216: 4,
 216029: 1,
 201823: 1,
 255793: 1,
 316577: 3,
 306459: 1,
 236664: 3,
 112387: 1,
 111192: 2,
 18043: 1,
 10841: 1,
 392764: 2,
 392707: 2,
 389861: 1,
 269117: 7,
 342186: 4,
 337277: 2,
 333712: 2,
 331633: 1,
 440201: 1,
 439396: 1,
 439375: 6,
 454332: 1,
 450785: 2,
 447372: 1,
 447017: 1,
 443453: 1,
 320123: 6,
 416597: 4,
 416457: 4,
 255722: 1,
 252325: 1,
 432475: 2,
 430753: 1,
 426961: 2,
 219971: 4,
 218036: 1,
 247004: 1,
 244918: 1,
 243270: 1,
 239056: 1,
 406760: 1,
 297774: 1,
 293669: 1,
 288446: 37,
 374527: 7,
 280793: 2,
 280789: 1,
 279605: 3,
 210117: 1,
 289211: 1,
 286739: 1,
 284593: 1,
 279374: 1,
 371266: 1,
 370984: 1,
 370639: 2,
 369233: 2,
 365623: 1,
 363786: 6,
 283241: 2,
 327307: 2,
 325272: 1,
 321626: 1,
 317774: 4,
 194349: 2,
 192815: 1,
 188494: 1,
 254838: 1,
 355979: 2,
 306715: 1,
 306015: 1,
 302715: 2,
 301896: 1,
 300893: 1,
 298644: 1,
 316816: 2,
 291077: 1,
 217866: 2,
 213020: 3,
 330702: 6,
 201130: 1,
 194177: 1,
 193220: 1,
 189844: 4,
 188401: 1,
 309018: 1,
 306534: 1,
 248799: 1,
 248536: 1,
 268603: 2,
 265299: 1,
 265100: 1,
 263093: 2,
 228228: 1,
 150463: 1,
 186369: 2,
 182759: 1,
 221665: 1,
 215831: 2,
 214519: 1,
 210579: 1,
 243460: 3,
 241822: 3,
 265936: 20,
 229078: 10,
 224489: 1,
 375999: 1,
 323627: 2,
 311591: 1,
 344026: 6,
 335404: 15,
 318172: 6,
 317286: 1,
 312546: 1,
 304640: 3,
 207001: 1,
 204074: 1,
 369613: 1,
 305957: 2,
 372406: 1,
 371828: 3,
 366811: 2,
 244269: 1,
 243693: 1,
 243593: 3,
 366086: 6,
 362268: 1,
 358638: 1,
 357523: 1,
 417665: 3,
 410937: 2,
 359089: 1,
 358244: 1,
 356796: 1,
 478946: 1,
 476244: 1,
 407141: 9,
 275130: 5,
 238569: 3,
 234688: 1,
 443152: 1,
 408568: 2,
 405434: 2,
 403842: 2,
 400383: 1,
 263811: 10,
 259922: 3,
 255634: 1,
 427874: 2,
 260600: 2,
 258614: 7,
 257312: 1,
 253786: 1,
 247247: 1,
 431712: 5,
 422138: 1,
 251323: 2,
 295627: 2,
 198298: 1,
 191257: 1,
 188269: 1,
 386920: 28,
 382371: 1,
 351047: 1,
 108741: 2,
 167095: 1,
 163069: 2,
 173921: 4,
 165091: 1,
 397251: 2,
 394174: 1,
 391788: 2,
 389536: 5,
 384512: 2,
 341877: 1,
 145919: 1,
 143868: 10,
 138217: 1,
 158618: 1,
 156752: 1,
 256601: 2,
 255329: 2,
 253291: 9,
 157249: 1,
 156204: 2,
 379934: 1,
 372456: 10,
 371373: 4,
 369656: 1,
 366741: 4,
 380786: 1,
 352072: 1,
 119301: 1,
 166401: 3,
 160295: 1,
 132741: 1,
 132030: 1,
 127556: 3,
 126077: 1,
 123469: 1,
 158387: 1,
 91461: 1,
 90690: 1,
 90613: 14,
 90225: 1,
 90066: 1,
 110544: 2,
 70861: 1,
 67399: 2,
 65968: 1,
 173276: 1,
 168507: 1,
 183783: 3,
 91703: 1,
 91679: 1,
 102776: 5,
 93621: 1,
 90056: 2,
 90008: 1,
 88705: 4,
 59392: 15,
 55290: 2,
 180489: 2,
 180267: 3,
 179843: 1,
 172730: 2,
 987: 1,
 75331: 1,
 65497: 1,
 104810: 1,
 100496: 3,
 88205: 2,
 34022: 1,
 42912: 1,
 13772: 2,
 6179: 7,
 5618: 1,
 2409: 2,
 1370: 5,
 177: 1,
 56678: 2,
 49184: 1,
 62870: 1,
 20149: 1,
 18160: 1,
 25734: 4,
 108920: 1,
 104315: 1,
 30183: 2,
 95012: 7,
 93625: 1,
 7099: 1,
 82300: 2,
 24244: 2,
 24053: 1,
 23658: 1,
 19177: 1,
 11023: 2,
 43057: 1,
 37087: 1,
 35844: 5,
 35342: 1,
 27160: 9,
 26414: 6,
 24187: 1,
 22655: 6,
 22234: 1,
 21909: 1,
 14288: 1,
 7884: 10,
 7331: 1,
 57457: 1,
 845132: 1,
 835910: 2,
 843131: 1,
 840123: 1,
 834395: 5,
 824973: 1,
 824889: 1,
 6191: 6,
 5313: 4,
 834272: 68,
 831486: 8,
 818490: 1,
 812432: 1,
 804870: 1,
 804775: 1,
 816805: 2,
 815545: 1,
 808819: 4,
 799606: 1,
 796986: 1,
 796450: 17,
 831655: 1,
 827440: 1,
 783192: 5,
 819820: 1,
 819574: 1,
 817255: 1,
 836798: 1,
 755285: 1,
 740425: 1,
 738630: 4,
 816496: 1,
 814264: 2,
 813214: 1,
 806418: 5,
 805222: 1,
 804678: 1,
 824246: 15,
 735944: 2,
 733763: 2,
 727446: 1,
 725707: 3,
 725170: 1,
 702021: 1,
 695248: 1,
 687911: 1,
 815034: 1,
 814055: 1,
 813811: 1,
 800002: 5,
 795247: 1,
 767837: 1,
 763955: 1,
 782361: 4,
 664561: 5,
 657903: 1,
 694906: 9,
 687798: 2,
 462260: 2,
 342670: 2,
 352313: 3,
 349720: 1,
 297371: 1,
 280151: 2,
 279999: 2,
 393909: 2,
 392486: 5,
 311065: 1,
 385081: 4,
 377704: 25,
 458292: 3,
 457827: 1,
 427807: 1,
 425392: 2,
 420727: 2,
 420532: 1,
 417001: 1,
 416514: 2,
 364188: 5,
 363968: 1,
 354566: 1,
 354151: 1,
 353805: 2,
 301298: 8,
 301099: 1,
 297807: 2,
 294051: 3,
 290964: 15,
 265189: 1,
 451912: 2,
 450765: 1,
 447447: 1,
 447286: 1,
 447153: 1,
 397686: 1,
 426519: 2,
 424599: 4,
 395760: 1,
 394181: 19,
 391552: 1,
 384376: 1,
 441948: 1,
 439649: 1,
 437471: 1,
 489548: 1,
 488441: 1,
 415470: 1,
 412131: 1,
 411425: 5,
 408018: 1,
 402644: 1,
 402245: 2,
 401297: 1,
 401022: 85,
 399267: 1,
 478447: 2,
 469743: 4,
 469439: 1,
 465126: 9,
 414484: 1,
 367959: 3,
 365417: 2,
 365254: 1,
 344794: 1,
 339498: 1,
 413626: 2,
 410831: 2,
 410006: 1,
 406087: 2,
 405834: 2,
 449133: 14,
 436583: 1,
 435459: 2,
 435445: 1,
 398347: 25,
 399382: 4,
 398779: 4,
 329894: 1,
 329303: 1,
 327556: 1,
 326858: 1,
 326480: 1,
 385970: 1,
 368515: 1,
 365259: 2,
 365191: 1,
 359070: 1,
 397503: 2,
 380202: 1,
 356665: 1,
 348161: 2,
 330919: 1,
 368342: 2,
 366769: 17,
 364330: 1,
 360577: 4,
 358966: 1,
 357771: 1,
 352071: 1,
 237462: 1,
 47274: 1,
 56866: 1,
 186359: 1,
 184038: 1,
 182963: 1,
 181588: 2,
 92901: 1,
 139854: 1,
 136759: 1,
 85665: 1,
 176949: 1,
 176912: 3,
 174822: 1,
 170238: 1,
 165359: 1,
 164107: 1,
 82696: 1,
 75914: 1,
 193028: 1,
 190675: 1,
 155424: 2,
 152811: 4,
 152799: 27,
 150674: 1,
 145547: 2,
 178980: 1,
 177482: 1,
 175575: 1,
 229103: 1,
 222359: 1,
 220303: 1,
 217511: 2,
 199133: 1,
 193551: 1,
 268594: 2,
 158136: 1,
 164607: 1,
 136351: 1,
 118995: 1,
 177910: 1,
 177376: 1,
 176537: 1,
 171358: 2,
 170470: 1,
 169693: 13,
 32467: 1,
 254854: 1,
 253310: 2,
 244484: 30,
 244190: 1,
 350889: 3,
 343797: 2,
 340466: 3,
 424421: 3,
 305070: 3,
 302845: 2,
 301112: 1,
 360759: 1,
 314864: 1,
 312348: 2,
 305488: 1,
 188789: 11,
 187792: 4,
 177038: 5,
 174487: 2,
 190274: 1,
 424170: 2,
 424091: 1,
 423657: 2,
 421491: 1,
 416628: 8,
 411561: 2,
 358654: 5,
 354400: 1,
 351567: 1,
 347006: 1,
 304101: 6,
 239071: 1,
 222445: 1,
 349235: 2,
 407594: 5,
 270196: 2,
 459964: 2,
 456577: 2,
 276812: 2,
 273754: 4,
 272685: 1,
 349644: 3,
 346340: 10,
 345398: 2,
 341269: 1,
 375500: 1,
 374697: 1,
 306852: 1,
 301084: 2,
 269681: 1,
 227581: 8,
 214537: 3,
 201882: 1,
 196476: 1,
 431682: 1,
 430706: 4,
 427177: 1,
 426317: 3,
 421563: 2,
 421345: 1,
 356691: 1,
 356484: 3,
 294666: 5,
 309928: 1,
 305180: 1,
 212985: 1,
 210813: 12,
 392142: 4,
 387930: 1,
 396245: 2,
 565843: 1,
 552920: 1,
 724125: 1,
 541165: 3,
 538509: 7,
 526882: 4,
 518558: 1,
 744085: 4,
 739065: 4,
 737532: 1,
 734188: 2,
 729751: 1,
 788540: 1,
 784638: 1,
 780777: 1,
 778861: 6,
 718365: 1,
 714811: 5,
 791588: 1,
 790625: 1,
 670274: 1,
 627118: 1,
 618724: 1,
 618397: 1,
 696737: 1,
 696270: 2,
 694817: 1,
 694506: 4,
 694230: 83,
 689486: 1,
 689090: 1,
 688437: 3,
 687410: 4,
 665817: 1,
 663110: 2,
 45178: 1,
 37125: 1,
 98220: 1,
 96124: 3,
 83207: 2,
 81248: 2,
 80240: 1,
 72411: 9,
 67866: 1,
 59229: 1,
 197: 5,
 48190: 1,
 48000: 1,
 46448: 2,
 40867: 1,
 40506: 2,
 30739: 1,
 28164: 1,
 19888: 1,
 15885: 7,
 10450: 1,
 9353: 1,
 7490: 1,
 5349: 7,
 4505: 2,
 4457: 44,
 838409: 6,
 829475: 1,
 822904: 34,
 843245: 2,
 841647: 11,
 832655: 1,
 828121: 1,
 839594: 1,
 830264: 1,
 816040: 1,
 814253: 2,
 253180: 5,
 130295: 1,
 127154: 1,
 126245: 2,
 123830: 5,
 799755: 2,
 809924: 9,
 809034: 13,
 806001: 1,
 803903: 4,
 844142: 1,
 843805: 1,
 841659: 1,
 832368: 1,
 830500: 1,
 832827: 2,
 831834: 2,
 830180: 1,
 826340: 3,
 826315: 2,
 826300: 1,
 785159: 1,
 729672: 4,
 756801: 3,
 775627: 1,
 795387: 7,
 793523: 1,
 758919: 1,
 777697: 1,
 748918: 1,
 745253: 9,
 743525: 1,
 742799: 1,
 742502: 6,
 738038: 2,
 737895: 1,
 736956: 1,
 736756: 4,
 713062: 3,
 815175: 7,
 811669: 1,
 808322: 2,
 807239: 1,
 806179: 1,
 768635: 1,
 797064: 5,
 795698: 6,
 709309: 1,
 701759: 2,
 696234: 1,
 770053: 3,
 767327: 2,
 786322: 1,
 782280: 7,
 192449: 2,
 16796: 1,
 14664: 1,
 12641: 6,
 116074: 1,
 754281: 1,
 749513: 1,
 114445: 1,
 108280: 1,
 159727: 2,
 159264: 1,
 158011: 1,
 157577: 2,
 208226: 17,
 182248: 4,
 132376: 2,
 122178: 2,
 121915: 1,
 120008: 1,
 113350: 1,
 155814: 3,
 150189: 2,
 171866: 3,
 169698: 4,
 177449: 1,
 175700: 1,
 170006: 1,
 210769: 1,
 204523: 2,
 122691: 8,
 112506: 2,
 152938: 1,
 197905: 2,
 196256: 1,
 89554: 1,
 78751: 1,
 78167: 4,
 76758: 1,
 68968: 1,
 66180: 1,
 840701: 1,
 834897: 1,
 830010: 2,
 829502: 3,
 824539: 13,
 634881: 1,
 626434: 9,
 619164: 1,
 618548: 2,
 614399: 4,
 688726: 3,
 669616: 7,
 813637: 5,
 795693: 1,
 840348: 11,
 835075: 6,
 833785: 10,
 829856: 1,
 782600: 2,
 782123: 1,
 782005: 1,
 776433: 2,
 773287: 1,
 770819: 3,
 769802: 1,
 768844: 1,
 822606: 1,
 821867: 1,
 21968: 1,
 18236: 28,
 13607: 1,
 826380: 10,
 825438: 6,
 825119: 2,
 741276: 1,
 802993: 3,
 800378: 1,
 821098: 1,
 819477: 1,
 809400: 4,
 796178: 2,
 795148: 1,
 788803: 1,
 787837: 1,
 299837: 3,
 293092: 1,
 288544: 1,
 286306: 1,
 331604: 3,
 541104: 1,
 535162: 3,
 377919: 4,
 374390: 1,
 515637: 7,
 508378: 1,
 506695: 1,
 504449: 2,
 362758: 1,
 384296: 1,
 377999: 1,
 306367: 1,
 299170: 2,
 493174: 1,
 502094: 1,
 247959: 4,
 236089: 1,
 232678: 3,
 273925: 4,
 265087: 2,
 285753: 1,
 283281: 1,
 280139: 8,
 279415: 2,
 278940: 1,
 278875: 2,
 276311: 1,
 298788: 1,
 297834: 8,
 335024: 1,
 329667: 1,
 328811: 2,
 323507: 3,
 322151: 5,
 258969: 1,
 258708: 1,
 253067: 1,
 359217: 7,
 208123: 14,
 317710: 5,
 316308: 34,
 203917: 7,
 319137: 1,
 309776: 1,
 194407: 3,
 349955: 3,
 669553: 15,
 572476: 1,
 772027: 1,
 752460: 8,
 640481: 14,
 640181: 1,
 562466: 1,
 559303: 1,
 430871: 2,
 430729: 1,
 357379: 1,
 444616: 2,
 439866: 1,
 435627: 1,
 434135: 38,
 433220: 15,
 439097: 3,
 436715: 3,
 507763: 1,
 505299: 1,
 331764: 1,
 330898: 15,
 329807: 13,
 426665: 3,
 395505: 1,
 395917: 1,
 385075: 1,
 383691: 2,
 376290: 1,
 330093: 4,
 328740: 1,
 327761: 1,
 646615: 1,
 391152: 2,
 390067: 1,
 394883: 1,
 390684: 3,
 464513: 1,
 458311: 1,
 457143: 11,
 449327: 1,
 356728: 1,
 255242: 1,
 253763: 2,
 247358: 1,
 384807: 3,
 384680: 2,
 382803: 1,
 350087: 1,
 343584: 6,
 343501: 4,
 340610: 1,
 393596: 2,
 393149: 1,
 406225: 4,
 339268: 2,
 301547: 1,
 164912: 1,
 158701: 4,
 205888: 1,
 201481: 1,
 113953: 1,
 111428: 1,
 105448: 1,
 156774: 2,
 157331: 2,
 151735: 3,
 149368: 4,
 144512: 1,
 154820: 2,
 249256: 5,
 246624: 6,
 238184: 2,
 132337: 1,
 99912: 1,
 124738: 4,
 80609: 1,
 181218: 1,
 179302: 3,
 59689: 1,
 55043: 1,
 191630: 1,
 185506: 2,
 182938: 41,
 180851: 7,
 115961: 2,
 95030: 1,
 87927: 4,
 87695: 1,
 86604: 2,
 86090: 1,
 88951: 1,
 79852: 1,
 75344: 2,
 69756: 2,
 136797: 1,
 135744: 1,
 50557: 3,
 61503: 1,
 299355: 5,
 483764: 1,
 483175: 2,
 479202: 2,
 476347: 1,
 189030: 2,
 187623: 1,
 179781: 7,
 468104: 4,
 410149: 3,
 268511: 1,
 475293: 4,
 292445: 1,
 291407: 2,
 287388: 4,
 463240: 1,
 460876: 3,
 271066: 1,
 215490: 1,
 204704: 1,
 199660: 2,
 198428: 1,
 167819: 3,
 837179: 12,
 834944: 1,
 831390: 1,
 842187: 2,
 840802: 1,
 838357: 3,
 831170: 1,
 825022: 2,
 844646: 3,
 843838: 5,
 689106: 1,
 684444: 4,
 788718: 1,
 803973: 1,
 680554: 1,
 670042: 1,
 666591: 1,
 766251: 1,
 791318: 2,
 788642: 1,
 783684: 1,
 736282: 1,
 731615: 1,
 731243: 1,
 751757: 1,
 750301: 1,
 724742: 2,
 721997: 1,
 718419: 8,
 715942: 2,
 715898: 1,
 714263: 1,
 630671: 1,
 677445: 1,
 676418: 2,
 754269: 1,
 750427: 1,
 468859: 1,
 468203: 2,
 465980: 1,
 461505: 1,
 455691: 1,
 453423: 1,
 448116: 1,
 438148: 3,
 435886: 3,
 452126: 2,
 447887: 9,
 439248: 1,
 437149: 2,
 432503: 6,
 451451: 1,
 446440: 1,
 439199: 1,
 456509: 8,
 455277: 1,
 440806: 1,
 423531: 1,
 422192: 1,
 430269: 1,
 421915: 2,
 ...}

In [15]:
cntsort = sorted(cnt.items(), key = lambda x:x[1], reverse=True)
print(cntsort[:10])

[(753343, 1700), (1965, 1195), (748308, 1123), (755981, 884), (768597, 813), (706924, 770), (839528, 756), (718416, 734), (826313, 733), (658747, 705)]

In [16]:
data1 = regionData[regionData['PD_C'] == 753343 ]
data2 = regionData[regionData['PD_C'] == 1965 ]
data3 = regionData[regionData['PD_C'] == 748308 ]
data4 = regionData[regionData['PD_C'] == 755981 ]
data5 = regionData[regionData['PD_C'] == 768597 ]
data6 = regionData[regionData['PD_C'] == 706924 ]
data7 = regionData[regionData['PD_C'] == 839528 ]
data8 = regionData[regionData['PD_C'] == 718416]
data9 = regionData[regionData['PD_C'] == 826313 ]
data10 = regionData[regionData['PD_C'] == 658747 ]


data1 = data1[:1]
data1
data2 = data2[:1]
data3 = data3[:1]
data4 = data4[:1]
data5 = data5[:1]
data6 = data6[:1]
data7 = data7[:1]
data8 = data8[:1]
data9 = data9[:1]
data10 = data10[:1]

In [17]:
rank = data1
rank = rank.append(data2)
rank = rank.append(data3)
rank = rank.append(data4)
rank = rank.append(data5)
rank = rank.append(data6)
rank = rank.append(data7)
rank = rank.append(data8)
rank = rank.append(data9)
rank = rank.append(data10)
rank

,Unnamed: 0,PD_C,PD_NM,CLAC1_NM,CLAC2_NM,CLAC3_NM,SESS_ID,PD_ADD_NM,PD_BRA_NM,DVC_CTG_NM,ZON_NM,CITY_NM
347613,347613,753343,남성 드로즈 15종 택1 - 06_CCCDRM92WN / 105,속옷/양말/홈웨어,남성속옷,남성팬티,1215019,상품명:06)CDCDRM92NY/사이즈:100,[코데즈컴바인 이너웨어],desktop,Jeollanam-do,Yeosu-si
3288506,3288506,1965,홍삼정 에브리타임(10mlx30포) / 롯데백화점 본점 출고 / 정관장,건강식품,홍삼/인삼가공식품,홍삼액,6195715,1개,정관장,mobile,Gyeonggi-do,Anyang
2871969,2871969,748308,립스틱 - 온 홀드,화장품/뷰티케어,메이크업,립스틱/립라이너,8340830,색상:디바,[맥],desktop,Seoul,Seoul
2515580,2515580,755981,홍삼정진(進) 에브리타임 10mx30포 + 쇼핑백 증정 - 홍삼정진에브리타임,건강식품,홍삼/인삼가공식품,홍삼/인삼혼합세트,906695,선택:홍삼정진에브리타임 / 1개,정관장.,mobile,Seoul,Seoul
1492943,1492943,768597,패턴/솔리드 남성 드로즈 30종 택1 - 004)EHD5671 / 100,속옷/양말/홈웨어,남성속옷,남성팬티,8511021,상품명:002)EHD5669|사이즈:100 / 1개,엘르이너웨어,mobile,Seoul,Seoul
616126,616126,706924,아몬드브리즈 오리지널 190ml 24팩 - 아몬드 브리즈 오리지널 190mlx24팩,음료,두유,일반두유,9826914,상품명:아몬드 브리즈 오리지널 190mlx24팩 / 1개,매일,mobile,Seoul,Seoul
3691549,3691549,839528,[당일배송] 2018 NEW UV플랩캡/캠핑햇 13종 택 1 - 10.캠핑햇_GRE...,패션잡화,모자,아동모,10710904,디자인:05.플랩캡_IVORY/사이즈:L,[베이비반즈],desktop,Seoul,Seoul
2852049,2852049,718416,홍삼정 240g 롯데백화점 본점 출고 / 정관장,건강식품,홍삼/인삼가공식품,홍삼액,9047304,1개,정관장,mobile,Jeollabuk-do,Gunsan-si
2115835,2115835,826313,풀무원 생수 2L x 6페트,음료,생수,생수,5101523,1개,웅진식품,mobile,Gwangju,Gwangju
5789682,5789682,658747,따뚜아쥬 꾸뛰르 타투틴트 - 15바이올렛 컨빅션,화장품/뷰티케어,메이크업,블러셔/쉐이딩/하이라이터,3881549,색상:16누드 엠블럼 / 1개,입생로랑,mobile,Gyeongsangnam-do,Yangsan-si

## 부산

In [47]:
busan_filter = regionData['ZON_NM']=='Busan'
print(regionData[busan_filter])

busan_data = regionData[busan_filter]
busan = busan_data['PD_C']
#busan[:2]

         Unnamed: 0    PD_C  \
10               10   61537
13               13   58820
18               18   58183
46               46  123395
52               52  209216
...             ...     ...
6183997     6183997  700904
6183999     6183999  700904
6184002     6184002  410356
6184003     6184003  409376
6184012     6184012  399225

                                                     PD_NM   CLAC1_NM  \
10                 닥터마틴 아드리안 블랙, 체리레드 - 02_체리레드 / 250mm(6)       패션잡화
13       여성 그레이 스트라이프 퍼프 소매 블라우스 (128865YQ33) - 회색(앤틱실버...       남성의류
18          [17S/S]  울 자카드 져지 자켓 9317111001056 - 네이비 / 100       남성의류
46                          네이비 하와이 5부 여성 파자마 EPF8678 - 90  속옷/양말/홈웨어
52       코튼 혼방 폴로 피케 반팔 티셔츠( TBMS1KTS23A0-B30) - B30 / ...      유아동의류
...                                                    ...        ...
6183997                                    가우퍼압력솥 6인용(통5중)    식기/조리기구
6183999                                    가우퍼압력솥 6인용(통5중)    식기/조리기구
6184002       별 패턴 실크 스카프 ATSC8E100 - P2(핑크) / 5X84(가로X세로)       패션잡화
6184003  팝바니 키즈 하트 스트라이프 클래식 티셔츠 화이트 - 팝바니키즈하트스트클래식티셔츠/...      유아동의류
6184012              링클플리츠주름밴딩스커트(CFHM1SK8821) - 블랙 / FREE       여성의류

        CLAC2_NM CLAC3_NM   SESS_ID                              PD_ADD_NM  \
10           남성화     남성부츠   2444196         제품:01_블랙|사이즈(UK):280mm(9) / 1개
13        남성의류상의   남성남방셔츠    395116                색상:회색(앤틱실버)|Size:M / 1개
18       남성의류아우터  남성캐주얼재킷    231275                     색상:네이비|사이즈:95 / 1개
46           홈웨어     여성잠옷   3680486                            사이즈:90 / 1개
52        남아의류상의  남아티셔츠/탑   7215749              색상:B30|직접입력2:06(120) / 1개
...          ...      ...       ...                                    ...
6183997     조리기구      압력솥   8211361                                     1개
6183999     조리기구      압력솥   8354002                                     1개
6184002   패션액세서리      스카프  10159688             색상:N2(네이비)/사이즈:5X84(가로X세로)
6184003   여아의류상의  여아티셔츠/탑  10266630  상품명/색상_사이즈:팝바니키즈하트스트클래식티셔츠/화이트9T / 1개
6184012   여성의류하의    여성스커트   3512543                         색상:블루/사이즈:FREE

         PD_BRA_NM DVC_CTG_NM ZON_NM CITY_NM
10            닥터마틴     mobile  Busan   Busan
13           에잇세컨즈     mobile  Busan   Busan
18         코모도(남성)     mobile  Busan   Busan
46          엘르이너웨어     mobile  Busan   Busan
52       타미힐피거 칠드런     mobile  Busan   Busan
...            ...        ...    ...     ...
6183997         풍년     mobile  Busan   Busan
6183999         풍년     mobile  Busan   Busan
6184002      [앳코너]    desktop  Busan   Busan
6184003     팬콧(키즈)     mobile  Busan   Busan
6184012      [포커스]    desktop  Busan   Busan

[676537 rows x 12 columns]

In [4]:
cnt = {}

for data in busan:
    try: cnt[data] +=1
    except: cnt[data] = 1
cnt

{61537: 1,
 58820: 1,
 58183: 1,
 123395: 1,
 209216: 2,
 216029: 2,
 213856: 1,
 206498: 1,
 202585: 1,
 255793: 1,
 316577: 3,
 312035: 1,
 306459: 1,
 237368: 1,
 236664: 2,
 111192: 2,
 24522: 1,
 10841: 1,
 392707: 1,
 337631: 2,
 333712: 1,
 331949: 2,
 439375: 1,
 455494: 1,
 455491: 1,
 454332: 1,
 450785: 1,
 443453: 2,
 320123: 3,
 416457: 1,
 426961: 1,
 219971: 1,
 241840: 2,
 240341: 1,
 288446: 20,
 280793: 2,
 279605: 1,
 210117: 4,
 288748: 1,
 284593: 1,
 232206: 2,
 371266: 2,
 370639: 1,
 363786: 7,
 283241: 2,
 278997: 1,
 321626: 2,
 318034: 1,
 317774: 6,
 199790: 2,
 187980: 1,
 241778: 1,
 304553: 1,
 300893: 1,
 298644: 1,
 291077: 1,
 213020: 1,
 330702: 1,
 296927: 1,
 290649: 1,
 288621: 1,
 201130: 1,
 194177: 2,
 189844: 3,
 188401: 1,
 261276: 1,
 337839: 2,
 226742: 2,
 187805: 1,
 186369: 2,
 223806: 1,
 210579: 1,
 243460: 1,
 241822: 5,
 265936: 9,
 221437: 1,
 221068: 1,
 375999: 1,
 327697: 1,
 344026: 2,
 335404: 12,
 463421: 1,
 318172: 4,
 304640: 3,
 301168: 1,
 205208: 1,
 371828: 2,
 245047: 1,
 243593: 1,
 366086: 4,
 410937: 5,
 359089: 1,
 356796: 2,
 479718: 1,
 478946: 1,
 475587: 2,
 407141: 4,
 400426: 2,
 275130: 1,
 238569: 2,
 403842: 1,
 263811: 2,
 259922: 3,
 427874: 1,
 260600: 4,
 258614: 2,
 431712: 3,
 425281: 1,
 393707: 1,
 251323: 2,
 118664: 1,
 295627: 2,
 198298: 1,
 191257: 1,
 188584: 3,
 386920: 9,
 382371: 2,
 167095: 1,
 389536: 1,
 384512: 1,
 341877: 2,
 143868: 12,
 158618: 1,
 256601: 4,
 376700: 1,
 372456: 5,
 371373: 2,
 369656: 1,
 355075: 1,
 352385: 1,
 352072: 3,
 166401: 1,
 163231: 2,
 123908: 2,
 123469: 2,
 91461: 1,
 90613: 2,
 90066: 1,
 110544: 1,
 177896: 3,
 173276: 2,
 99526: 2,
 102776: 2,
 61240: 1,
 59392: 7,
 52043: 1,
 51216: 1,
 180489: 3,
 4645: 1,
 1546: 1,
 82547: 2,
 81219: 1,
 104131: 4,
 100696: 2,
 100496: 1,
 23502: 1,
 44640: 1,
 6179: 4,
 5618: 1,
 5058: 1,
 2409: 4,
 1370: 1,
 44533: 1,
 43813: 1,
 76450: 1,
 28780: 2,
 25734: 1,
 108920: 1,
 104315: 1,
 45470: 1,
 36431: 1,
 34656: 1,
 32822: 1,
 26471: 1,
 95012: 2,
 90863: 1,
 87382: 1,
 86406: 1,
 7099: 1,
 984: 1,
 81432: 1,
 23658: 1,
 19177: 2,
 35844: 3,
 31218: 3,
 30906: 1,
 27160: 5,
 26414: 4,
 22655: 5,
 14288: 1,
 13262: 1,
 8307: 1,
 7884: 6,
 64895: 1,
 63658: 1,
 62421: 1,
 57457: 1,
 56621: 1,
 834395: 2,
 834278: 1,
 826914: 3,
 824889: 1,
 824228: 1,
 823361: 6,
 6191: 1,
 5313: 2,
 834272: 32,
 831486: 10,
 816805: 2,
 810755: 2,
 808819: 7,
 796450: 11,
 791653: 2,
 783192: 5,
 777132: 1,
 819820: 1,
 819574: 1,
 756540: 1,
 745503: 1,
 738630: 2,
 813867: 1,
 806418: 6,
 824246: 10,
 733763: 1,
 727446: 1,
 702021: 2,
 690394: 1,
 800002: 6,
 767837: 1,
 656590: 1,
 694906: 6,
 690763: 1,
 690429: 3,
 687798: 4,
 463796: 4,
 462260: 1,
 352313: 2,
 349720: 1,
 295590: 1,
 393909: 1,
 392486: 1,
 387700: 1,
 311065: 1,
 385081: 2,
 377704: 19,
 457827: 2,
 334072: 3,
 425392: 2,
 420727: 3,
 416978: 1,
 366783: 2,
 364188: 1,
 362190: 1,
 358998: 2,
 354625: 1,
 354566: 1,
 353805: 2,
 308651: 1,
 308359: 1,
 301298: 1,
 297807: 4,
 294051: 4,
 290964: 6,
 455227: 1,
 452396: 2,
 451912: 1,
 447447: 4,
 446618: 1,
 425559: 4,
 424599: 1,
 394181: 12,
 489975: 1,
 411425: 4,
 402245: 2,
 401022: 49,
 477536: 1,
 469439: 1,
 465126: 4,
 409262: 1,
 369358: 2,
 367959: 2,
 365417: 3,
 363717: 1,
 453440: 1,
 453342: 1,
 344794: 1,
 339498: 3,
 336443: 1,
 413815: 1,
 412143: 1,
 410831: 1,
 410006: 4,
 407538: 1,
 406087: 1,
 449133: 11,
 440974: 1,
 440903: 1,
 436583: 1,
 435459: 2,
 398347: 23,
 400994: 1,
 399382: 1,
 398779: 1,
 390035: 1,
 368515: 4,
 387544: 1,
 373711: 1,
 376025: 1,
 353515: 1,
 353170: 1,
 324366: 2,
 370167: 2,
 366769: 11,
 360577: 1,
 321619: 1,
 461116: 1,
 237225: 1,
 232413: 1,
 186359: 2,
 95842: 1,
 92901: 1,
 138484: 1,
 136506: 1,
 87348: 1,
 85665: 1,
 177328: 1,
 174822: 1,
 165359: 1,
 165271: 1,
 80375: 1,
 161547: 1,
 155424: 1,
 152799: 22,
 150788: 2,
 63553: 1,
 175575: 2,
 226756: 1,
 223684: 1,
 217511: 2,
 268747: 1,
 152394: 1,
 172636: 1,
 161570: 1,
 127239: 1,
 118995: 4,
 177376: 1,
 175736: 1,
 171358: 1,
 169693: 14,
 254854: 1,
 252209: 1,
 250533: 1,
 244484: 4,
 350889: 1,
 424421: 1,
 305070: 1,
 296842: 2,
 314864: 1,
 308938: 1,
 305488: 1,
 304136: 2,
 188789: 5,
 187792: 1,
 177038: 1,
 416628: 3,
 411561: 2,
 358654: 2,
 347006: 1,
 218535: 1,
 176009: 1,
 171911: 1,
 331285: 2,
 290456: 1,
 217696: 1,
 459964: 1,
 458140: 2,
 457291: 2,
 456820: 1,
 456407: 1,
 276812: 5,
 273754: 1,
 349644: 2,
 346340: 6,
 345398: 5,
 345397: 1,
 341269: 2,
 373209: 2,
 306152: 1,
 269681: 2,
 227581: 4,
 214537: 3,
 196476: 1,
 430706: 3,
 427177: 1,
 421317: 1,
 356484: 2,
 294666: 1,
 305180: 1,
 212985: 1,
 210813: 13,
 392142: 1,
 387930: 1,
 387125: 2,
 386666: 2,
 549732: 1,
 719644: 1,
 541165: 2,
 538509: 4,
 536566: 1,
 526882: 2,
 744085: 3,
 739065: 2,
 737532: 1,
 734373: 1,
 732912: 1,
 565934: 1,
 781172: 1,
 778861: 2,
 714811: 4,
 670274: 1,
 627118: 4,
 618724: 1,
 694506: 1,
 694230: 46,
 689090: 1,
 688558: 1,
 688437: 2,
 43847: 2,
 40732: 1,
 25185: 1,
 23983: 1,
 98220: 1,
 96124: 1,
 83688: 1,
 81248: 1,
 79966: 2,
 72411: 20,
 197: 5,
 49962: 1,
 46448: 1,
 40867: 1,
 28164: 1,
 26422: 1,
 15885: 3,
 9353: 1,
 5349: 3,
 4505: 1,
 4457: 16,
 838409: 1,
 837737: 1,
 822904: 17,
 822615: 3,
 842097: 1,
 841647: 4,
 829314: 1,
 847295: 1,
 842358: 1,
 832577: 2,
 816040: 1,
 814253: 4,
 126940: 1,
 123830: 1,
 799755: 1,
 809924: 3,
 809034: 5,
 806050: 1,
 803903: 1,
 803339: 1,
 841508: 2,
 843805: 2,
 838521: 1,
 832368: 1,
 831834: 2,
 826340: 1,
 826315: 7,
 783876: 1,
 825164: 1,
 817370: 1,
 729672: 4,
 756801: 1,
 775627: 1,
 795387: 1,
 758919: 1,
 749151: 1,
 748918: 2,
 745253: 8,
 743525: 1,
 742502: 2,
 736756: 3,
 713062: 2,
 785037: 3,
 808322: 1,
 768635: 1,
 797064: 4,
 795698: 3,
 707172: 1,
 771513: 1,
 767327: 2,
 628712: 1,
 782280: 3,
 815976: 1,
 12641: 8,
 157358: 1,
 208226: 1,
 182248: 2,
 122178: 2,
 121915: 1,
 120217: 2,
 120008: 1,
 113350: 1,
 155814: 1,
 171866: 2,
 169698: 1,
 210769: 2,
 122691: 2,
 156933: 1,
 155982: 1,
 202254: 1,
 201243: 1,
 78167: 1,
 845046: 1,
 830010: 1,
 829502: 2,
 824539: 10,
 823867: 1,
 616664: 1,
 615521: 1,
 688726: 1,
 669616: 4,
 813637: 4,
 840348: 7,
 839789: 1,
 835075: 13,
 833785: 7,
 829856: 1,
 828668: 1,
 782600: 1,
 782123: 2,
 782005: 1,
 776433: 2,
 826547: 1,
 822606: 1,
 821867: 2,
 811359: 1,
 810864: 1,
 18786: 1,
 18281: 1,
 18236: 13,
 760931: 2,
 826380: 9,
 825119: 1,
 807242: 1,
 821479: 1,
 821098: 1,
 809400: 2,
 807248: 1,
 788803: 1,
 807094: 1,
 290133: 1,
 286405: 1,
 281535: 1,
 337394: 1,
 331604: 2,
 541104: 3,
 539029: 2,
 535162: 1,
 515637: 4,
 507645: 1,
 506695: 1,
 357979: 1,
 380623: 2,
 304461: 1,
 299170: 1,
 502094: 3,
 247959: 6,
 232678: 5,
 375922: 1,
 273925: 3,
 489174: 2,
 217354: 1,
 283281: 1,
 280139: 6,
 278875: 3,
 276734: 1,
 276311: 1,
 297834: 1,
 335024: 1,
 329667: 1,
 324227: 2,
 322151: 1,
 259658: 1,
 258708: 1,
 359217: 4,
 354989: 2,
 208123: 9,
 317710: 5,
 316308: 9,
 313867: 1,
 320231: 1,
 309776: 1,
 343110: 1,
 669553: 14,
 667047: 1,
 772912: 1,
 765499: 1,
 752460: 3,
 640481: 15,
 562443: 1,
 557709: 1,
 430729: 3,
 434135: 17,
 433220: 18,
 442997: 1,
 436715: 3,
 507763: 3,
 505299: 1,
 330898: 11,
 329807: 13,
 426665: 1,
 405597: 1,
 395505: 1,
 376290: 1,
 330093: 10,
 606653: 1,
 646085: 1,
 391152: 3,
 390684: 7,
 457143: 4,
 356728: 1,
 353258: 1,
 253763: 1,
 247358: 1,
 384680: 1,
 343584: 1,
 343501: 1,
 413732: 1,
 411208: 1,
 406225: 1,
 343273: 1,
 169297: 1,
 165974: 1,
 142828: 1,
 113953: 2,
 113673: 1,
 159835: 1,
 155151: 1,
 157331: 2,
 151735: 2,
 149368: 1,
 153514: 1,
 246624: 3,
 238184: 2,
 101947: 1,
 124738: 1,
 80609: 2,
 64529: 1,
 55113: 1,
 191630: 3,
 185967: 1,
 185506: 3,
 182938: 22,
 180851: 8,
 115961: 1,
 110225: 1,
 87927: 5,
 86604: 1,
 86090: 1,
 73935: 1,
 50783: 7,
 50557: 1,
 61503: 2,
 299355: 7,
 483764: 1,
 483175: 1,
 179781: 9,
 468104: 4,
 467415: 1,
 189417: 1,
 410149: 4,
 475293: 1,
 291407: 2,
 176351: 1,
 463240: 1,
 461135: 2,
 202263: 1,
 258837: 1,
 834944: 1,
 843864: 2,
 840802: 1,
 838522: 1,
 827812: 1,
 825835: 1,
 843838: 2,
 689106: 1,
 789845: 2,
 799677: 1,
 670042: 1,
 766251: 1,
 718419: 4,
 787294: 1,
 618651: 1,
 614366: 1,
 676418: 2,
 750427: 1,
 742174: 2,
 465935: 1,
 462211: 2,
 461505: 1,
 455691: 1,
 438148: 2,
 452126: 1,
 447887: 6,
 441734: 1,
 438649: 1,
 432503: 5,
 453238: 2,
 456509: 4,
 455277: 3,
 430269: 2,
 421915: 2,
 433453: 1,
 414830: 2,
 438112: 1,
 435773: 1,
 433927: 2,
 430648: 1,
 342627: 1,
 240481: 1,
 236919: 1,
 236303: 1,
 229430: 2,
 388622: 3,
 350855: 4,
 422485: 2,
 417491: 1,
 415521: 1,
 299360: 9,
 296306: 1,
 308892: 1,
 306754: 1,
 303146: 2,
 244431: 2,
 243811: 1,
 230172: 2,
 353440: 4,
 352646: 3,
 336302: 1,
 332166: 11,
 387704: 8,
 386576: 1,
 225653: 3,
 268840: 1,
 345857: 2,
 344935: 2,
 341712: 2,
 337656: 1,
 328157: 4,
 327924: 1,
 324243: 1,
 415706: 1,
 415255: 2,
 492508: 1,
 365026: 1,
 472190: 3,
 521551: 2,
 519344: 1,
 502804: 4,
 265177: 1,
 259099: 1,
 405562: 4,
 402500: 1,
 347074: 1,
 408266: 1,
 405169: 1,
 404256: 2,
 344263: 1,
 342025: 1,
 341389: 1,
 340207: 1,
 443062: 16,
 395235: 6,
 388936: 1,
 432921: 1,
 430192: 1,
 426676: 1,
 193139: 1,
 193013: 1,
 191990: 1,
 446382: 1,
 247507: 3,
 184868: 1,
 309717: 2,
 305249: 3,
 302626: 1,
 286562: 4,
 432512: 2,
 420144: 2,
 415311: 1,
 410489: 1,
 290077: 1,
 282146: 1,
 281697: 2,
 275658: 1,
 274831: 1,
 279191: 3,
 262327: 1,
 400004: 1,
 398209: 2,
 230474: 1,
 224737: 2,
 396951: 1,
 478739: 1,
 473858: 8,
 376307: 1,
 371649: 1,
 369992: 3,
 468349: 3,
 464561: 1,
 456567: 1,
 265393: 2,
 259129: 3,
 366599: 1,
 233947: 3,
 219766: 1,
 320565: 1,
 320286: 4,
 213070: 1,
 212512: 2,
 210626: 1,
 210442: 1,
 210177: 3,
 207808: 1,
 196583: 1,
 194972: 1,
 189155: 1,
 345943: 2,
 335454: 5,
 331019: 1,
 174296: 1,
 167878: 1,
 309424: 1,
 302061: 1,
 108721: 2,
 426883: 2,
 426787: 1,
 413500: 2,
 299604: 1,
 295800: 1,
 338966: 1,
 334853: 1,
 198642: 1,
 198439: 1,
 405493: 1,
 518463: 2,
 59276: 1,
 58561: 1,
 103385: 2,
 99906: 1,
 97956: 1,
 119273: 1,
 45952: 1,
 112106: 1,
 75133: 1,
 89246: 2,
 74062: 2,
 70167: 1,
 122207: 3,
 120313: 1,
 39425: 1,
 38386: 1,
 72679: 1,
 64959: 4,
 64455: 1,
 62284: 2,
 62176: 1,
 322016: 1,
 55854: 3,
 236211: 1,
 257196: 2,
 55978: 2,
 275850: 1,
 272976: 1,
 260754: 1,
 51440: 1,
 51131: 1,
 154764: 1,
 142945: 1,
 296422: 1,
 89451: 1,
 88887: 2,
 88342: 2,
 86410: 1,
 85295: 1,
 80092: 1,
 616174: 1,
 613404: 2,
 613279: 2,
 739937: 6,
 733572: 3,
 809175: 1,
 807482: 2,
 806392: 2,
 805561: 1,
 745344: 5,
 740405: 5,
 737819: 7,
 736773: 1,
 712978: 2,
 802852: 7,
 801923: 1,
 727656: 2,
 725803: 1,
 797291: 1,
 793068: 2,
 788127: 1,
 91952: 1,
 87982: 1,
 82232: 1,
 81621: 1,
 715511: 6,
 712715: 1,
 710074: 4,
 704801: 1,
 579794: 94,
 657080: 1,
 656771: 1,
 652073: 6,
 650467: 3,
 685994: 1,
 685269: 1,
 679983: 1,
 518184: 1,
 517794: 1,
 516091: 1,
 516074: 1,
 580304: 2,
 596728: 2,
 596695: 8,
 328386: 3,
 319824: 1,
 314347: 3,
 374455: 1,
 372794: 1,
 368639: 1,
 510979: 40,
 312942: 1,
 302905: 12,
 302892: 1,
 301632: 1,
 251004: 1,
 567865: 2,
 564925: 2,
 494587: 2,
 437273: 2,
 434953: 2,
 515095: 1,
 514463: 1,
 482456: 2,
 482008: 1,
 478734: 1,
 477387: 1,
 470624: 1,
 510660: 1,
 505282: 2,
 502653: 1,
 500934: 1,
 305455: 2,
 354741: 1,
 346323: 1,
 296508: 1,
 236529: 1,
 175530: 1,
 174238: 2,
 284990: 1,
 279609: 4,
 278369: 3,
 277796: 1,
 502025: 2,
 499973: 2,
 495845: 1,
 229453: 1,
 219353: 1,
 423571: 1,
 421717: 1,
 350844: 6,
 349007: 1,
 551094: 1,
 550557: 2,
 540071: 1,
 538855: 1,
 535824: 2,
 331892: 1,
 846992: 5,
 455990: 3,
 442821: 2,
 560611: 1,
 609970: 2,
 713283: 1,
 710131: 1,
 708860: 2,
 ...}

In [5]:
cntsortt = sorted(cnt.items(), key = lambda x:x[1], reverse=True)
print(cntsortt[:10])

[(622881, 2706), (753343, 1452), (759894, 1274), (748308, 906), (816301, 844), (1965, 796), (759267, 727), (365667, 631), (755981, 618), (768597, 558)]

In [6]:
data1 = regionData[regionData['PD_C'] == 622881 ]
data2 = regionData[regionData['PD_C'] == 753343 ]
data3 = regionData[regionData['PD_C'] == 759894 ]
data4 = regionData[regionData['PD_C'] == 748308 ]
data5 = regionData[regionData['PD_C'] == 816301 ]
data6 = regionData[regionData['PD_C'] == 1965 ]
data7 = regionData[regionData['PD_C'] == 759267 ]
data8 = regionData[regionData['PD_C'] == 365667 ]
data9 = regionData[regionData['PD_C'] == 755981 ]
data10 = regionData[regionData['PD_C'] == 768597 ]


data1 = data1[:1]
data2 = data2[:1]
data3 = data3[:1]
data4 = data4[:1]
data5 = data5[:1]
data6 = data6[:1]
data7 = data7[:1]
data8 = data8[:1]
data9 = data9[:1]
data10 = data10[:1]

In [7]:
rank = data1
rank = rank.append(data2)
rank = rank.append(data3)
rank = rank.append(data4)
rank = rank.append(data5)
rank = rank.append(data6)
rank = rank.append(data7)
rank = rank.append(data8)
rank = rank.append(data9)
rank = rank.append(data10)
rank

,Unnamed: 0,PD_C,PD_NM,CLAC1_NM,CLAC2_NM,CLAC3_NM,SESS_ID,PD_ADD_NM,PD_BRA_NM,DVC_CTG_NM,ZON_NM,CITY_NM
3992676,3992676,622881,[선미 공항패션]Taylor mini O5NBCB08_PW - BLACK,패션잡화,여성가방,여성토트백,1856814,COLOR:CREAM / 1개,오야니(가방),mobile,Busan,Busan
347613,347613,753343,남성 드로즈 15종 택1 - 06_CCCDRM92WN / 105,속옷/양말/홈웨어,남성속옷,남성팬티,1215019,상품명:06)CDCDRM92NY/사이즈:100,[코데즈컴바인 이너웨어],desktop,Jeollanam-do,Yeosu-si
4842152,4842152,759894,테일러 MID(Taylor MID)O6FBCB22_PB - CREAM,패션잡화,여성가방,여성숄더백,4309492,COLOR:DUSTY LILAC / 1개,오야니,mobile,Busan,Busan
2871969,2871969,748308,립스틱 - 온 홀드,화장품/뷰티케어,메이크업,립스틱/립라이너,8340830,색상:디바,[맥],desktop,Seoul,Seoul
5304746,5304746,816301,선미 공항패션 Taylor mini O5NBCB08 - METALIC SILVER,패션잡화,여성가방,여성크로스백,8695790,COLOR:DUSTY GREY,[오야니],mobile,Busan,Busan
3288506,3288506,1965,홍삼정 에브리타임(10mlx30포) / 롯데백화점 본점 출고 / 정관장,건강식품,홍삼/인삼가공식품,홍삼액,6195715,1개,정관장,mobile,Gyeonggi-do,Anyang
3354410,3354410,759267,Taylor mini O5NBCB08_PB - PEWTER,패션잡화,여성가방,여성크로스백,5062019,색상:CREAM / 1개,오야니(가방),mobile,Busan,Busan
3539671,3539671,365667,[LAP] #핫한반팔T 모음 18종택1(LAP_0416) - 14_AJGWT039_...,여성의류,여성의류상의,여성티셔츠/탑,5814764,색상:06_AJGWT021_RE|사이즈:F / 1개,랩,mobile,Seoul,Seoul
2515580,2515580,755981,홍삼정진(進) 에브리타임 10mx30포 + 쇼핑백 증정 - 홍삼정진에브리타임,건강식품,홍삼/인삼가공식품,홍삼/인삼혼합세트,906695,선택:홍삼정진에브리타임 / 1개,정관장.,mobile,Seoul,Seoul
1492943,1492943,768597,패턴/솔리드 남성 드로즈 30종 택1 - 004)EHD5671 / 100,속옷/양말/홈웨어,남성속옷,남성팬티,8511021,상품명:002)EHD5669|사이즈:100 / 1개,엘르이너웨어,mobile,Seoul,Seoul

### 제주도!

In [48]:
jeju_filter = regionData['ZON_NM']=='Jeju-do'
print(regionData[jeju_filter])

jeju_data = regionData[jeju_filter]
jeju = jeju_data['PD_C']
#jeju[:1]

         Unnamed: 0    PD_C  \
75               75  209216
129             129  316577
191             191   15370
304             304  439375
317             317  454332
...             ...     ...
6183190     6183190  120662
6183321     6183321   48995
6183500     6183500  174135
6183511     6183511  119425
6183934     6183934   58550

                                                     PD_NM    CLAC1_NM  \
75       코튼 혼방 폴로 피케 반팔 티셔츠( TBMS1KTS23A0-B30) - B30 / ...       유아동의류
129      나이키 퓨추라 로고 반팔티 2종 택1 696707 화이트/네이비 - 나이키 퓨추라 ...       스포츠패션
191                Borgonovo 이탈리아 디자인 글라스 프렉티카볼 10cm 6p 세트     식기/조리기구
304      여성 GUESS LOSANGELES 플라워 PVC 반팔(YI2K6425) - 라이트...        남성의류
317                               {16D2_18S0032}런닝 - 핑크/70       유아동의류
...                                                    ...         ...
6183190                      이동식 2단 빨래바구니 - A.이동식 2단 빨래바구니  청소/세탁/욕실용품
6183321   W몰 씨씨콜렉트 프릴장식 머스터드 블라우스 E174MSC031MS - 머스터드 / 55        여성의류
6183500                                핑크팬더 쿨 메쉬 티-블루 - SM       원예/애완
6183511                           보타닉블루 커피잔 2인조+티백2p세트(BO)     식기/조리기구
6183934  [페리젠슨]스트레치 노턱 캐주얼팬츠 그레이.NPD17105 - 면바지.NPD1710...        남성의류

          CLAC2_NM   CLAC3_NM  SESS_ID  \
75          남아의류상의    남아티셔츠/탑  6456777
129      남성일반스포츠의류   남성스포츠티셔츠  7288889
191          그릇/식기       대접/볼  5119676
304         남성의류상의      남성티셔츠  5942285
317         여아의류상의    여아티셔츠/탑  8319823
...            ...        ...      ...
6183190       정리용품        바구니  6687004
6183321     여성의류상의     여성남방셔츠  1918433
6183500       애견용품  애견의류/악세서리   749027
6183511      그릇/식기        커피잔  1284906
6183934     남성의류하의    남성캐주얼바지   321991

                                                PD_ADD_NM  PD_BRA_NM  \
75                              색상:B30|직접입력2:14(160) / 1개  타미힐피거 칠드런
129      모델:나이키 퓨추라 로고 반팔티|사이즈:696707-106_화이트 M(100) / 1개    나이키(의류)
191                                                    1개      보르고노보
304                             색상:라이트핑크(LPI)|사이즈:XS / 1개    게스(VIP)
317                                          색상/사이즈:핑크/65     [로엠걸즈]
...                                                   ...        ...
6183190                           모델명:A.이동식 2단 빨래바구니 / 1개        리벤스
6183321                                    컬러:머스터드/사이즈:55    [씨씨콜렉트]
6183500                                        사이즈:L / 1개        이츠독
6183511                                                1개      포트메리온
6183934              선택:면바지.NPD17105 GRAY|사이즈:92(36) / 1개       페리젠슨

        DVC_CTG_NM   ZON_NM      CITY_NM
75          mobile  Jeju-do      Jeju-si
129         mobile  Jeju-do      Jeju-si
191         mobile  Jeju-do      Jeju-si
304         mobile  Jeju-do      Jeju-si
317         mobile  Jeju-do      Jeju-si
...            ...      ...          ...
6183190     mobile  Jeju-do      Jeju-si
6183321    desktop  Jeju-do  Seogwipo-si
6183500     mobile  Jeju-do      Jeju-si
6183511     mobile  Jeju-do      Jeju-si
6183934     mobile  Jeju-do      Jeju-si

[47228 rows x 12 columns]

In [63]:
cnt = {}

for data in jeju:
    try: cnt[data] +=1
    except: cnt[data] = 1
#cnt

In [64]:
cntsortt = sorted(cnt.items(), key = lambda x:x[1], reverse=True)
print(cntsortt[:10])

[(753343, 149), (736941, 62), (748308, 48), (768597, 46), (1965, 46), (427578, 41), (692709, 39), (755981, 38), (737743, 34), (409938, 34)]

In [65]:
data1 = regionData[regionData['PD_C'] == 753343 ]
data2 = regionData[regionData['PD_C'] == 736941 ]
data3 = regionData[regionData['PD_C'] == 748308 ]
data4 = regionData[regionData['PD_C'] == 768597 ]
data5 = regionData[regionData['PD_C'] == 1965 ]
data6 = regionData[regionData['PD_C'] == 427578 ]
data7 = regionData[regionData['PD_C'] == 692709 ]
data8 = regionData[regionData['PD_C'] ==755981]
data9 = regionData[regionData['PD_C'] == 737743 ]
data10 = regionData[regionData['PD_C'] == 409938 ]


data1 = data1[:1]
data2 = data2[:1]
data3 = data3[:1]
data4 = data4[:1]
data5 = data5[:1]
data6 = data6[:1]
data7 = data7[:1]
data8 = data8[:1]
data9 = data9[:1]
data10 = data10[:1]

In [66]:
rank = data1
rank = rank.append(data2)
rank = rank.append(data3)
rank = rank.append(data4)
rank = rank.append(data5)
rank = rank.append(data6)
rank = rank.append(data7)
rank = rank.append(data8)
rank = rank.append(data9)
rank = rank.append(data10)
rank

,Unnamed: 0,PD_C,PD_NM,CLAC1_NM,CLAC2_NM,CLAC3_NM,SESS_ID,PD_ADD_NM,PD_BRA_NM,DVC_CTG_NM,ZON_NM,CITY_NM
347613,347613,753343,남성 드로즈 15종 택1 - 06_CCCDRM92WN / 105,속옷/양말/홈웨어,남성속옷,남성팬티,1215019,상품명:06)CDCDRM92NY/사이즈:100,[코데즈컴바인 이너웨어],desktop,Jeollanam-do,Yeosu-si
1340494,1340494,736941,래스팅 실크 UV 파운데이션 SPF20 (30ml) - 8호,화장품/뷰티케어,메이크업,BB/파운데이션/컴팩트류,7514532,색상:4호 / 1개,조르지오 아르마니,mobile,Seoul,Seoul
2871969,2871969,748308,립스틱 - 온 홀드,화장품/뷰티케어,메이크업,립스틱/립라이너,8340830,색상:디바,[맥],desktop,Seoul,Seoul
1492943,1492943,768597,패턴/솔리드 남성 드로즈 30종 택1 - 004)EHD5671 / 100,속옷/양말/홈웨어,남성속옷,남성팬티,8511021,상품명:002)EHD5669|사이즈:100 / 1개,엘르이너웨어,mobile,Seoul,Seoul
3288506,3288506,1965,홍삼정 에브리타임(10mlx30포) / 롯데백화점 본점 출고 / 정관장,건강식품,홍삼/인삼가공식품,홍삼액,6195715,1개,정관장,mobile,Gyeonggi-do,Anyang
992717,992717,427578,여성 베이직 밴딩 브라팬티 4종 택1 - 01)CDBBRM51NY/set / 80B/90,속옷/양말/홈웨어,여성속옷,여성속옷세트,1672199,상품명:04)CDBBRM51RD/set|사이즈:80A/100 / 1개,코데즈컴바인 이너웨어,mobile,Daejeon,Daejeon
838092,838092,692709,에어팟 케이스 고리형 키링 행 - 러블리 핑크,모바일,모바일액세서리,기타모바일액세서리,5350493,색상:러블리 핑크 / 1개,엘라고,mobile,Seoul,Seoul
2515580,2515580,755981,홍삼정진(進) 에브리타임 10mx30포 + 쇼핑백 증정 - 홍삼정진에브리타임,건강식품,홍삼/인삼가공식품,홍삼/인삼혼합세트,906695,선택:홍삼정진에브리타임 / 1개,정관장.,mobile,Seoul,Seoul
2918704,2918704,737743,[리필] 르 쿠션 엉크르 드 뽀 SPF23 PA++ 14g - 40,화장품/뷰티케어,메이크업,BB/파운데이션/컴팩트류,9706493,색상:10 / 1개,입생로랑,mobile,Busan,Busan
4871955,4871955,409938,[지오다노] 018501 반팔 피케 폴로 - 14코랄오렌지 / S,남성의류,남성의류상의,남성티셔츠,3491830,색상:12옐로우/사이즈:S,[지오다노],desktop,Busan,Busan

## 경상남도

In [67]:
gnam_filter = regionData['ZON_NM']=='Gyeongsangnam-do'
print(regionData[gnam_filter])

gnam_data = regionData[gnam_filter]
gnam = gnam_data['PD_C']

         Unnamed: 0    PD_C  \
6                 6   62282
51               51  209216
61               61  209216
62               62  209216
98               98  209786
...             ...     ...
6183827     6183827    9449
6183894     6183894    3782
6183944     6183944  134893
6183981     6183981  707873
6184005     6184005  400890

                                                     PD_NM   CLAC1_NM  \
6                               여자 플라워덧신 2족선물세트 17403-2set  속옷/양말/홈웨어
51       코튼 혼방 폴로 피케 반팔 티셔츠( TBMS1KTS23A0-B30) - B30 / ...      유아동의류
61       코튼 혼방 폴로 피케 반팔 티셔츠( TBMS1KTS23A0-B30) - B30 / ...      유아동의류
62       코튼 혼방 폴로 피케 반팔 티셔츠( TBMS1KTS23A0-B30) - B30 / ...      유아동의류
98                                              쿠키커터클래식 6P       주방잡화
...                                                    ...        ...
6183827                             아카데미과학-다빈치 가변대포 18142A         완구
6183894  나이스독서대 오103/대 407mm x 268mm/독서대/고급독서대/책받침대/책거치...    문구/사무용품
6183944                 이중카라 세일러블라우스 NWBLIG6300 - 네이비 / 55       여성의류
6183981                    진주 반팔 블라우스 BLI159 - 아이보리 / Free       여성의류
6184005               아디다스 D2M 로고 반팔티셔츠 (BK0937) - 105(XL)      스포츠패션

          CLAC2_NM  CLAC3_NM  SESS_ID                PD_ADD_NM    PD_BRA_NM  \
6            여성양말류    여성일반양말   733100                       4개     안스엉클(양말)
51          남아의류상의   남아티셔츠/탑  5397796     색상:B30/직접입력2:06(120)  [타미힐피거 칠드런]
61          남아의류상의   남아티셔츠/탑  6501206     색상:B30/직접입력2:16(170)  [타미힐피거 칠드런]
62          남아의류상의   남아티셔츠/탑  6501206     색상:B30/직접입력2:16(170)  [타미힐피거 칠드런]
98            조리도구      제빵용품  2199884                       1개       스타베이커리
...            ...       ...      ...                      ...          ...
6183827       남아완구   조립/프라모델  9980861                       1개         아카데미
6183894  일반문구/사무용품       독서대  9257139  선택:나이스독서대 (오103)_대 / 1개          나이스
6183944     여성의류상의    여성남방셔츠  1976303      색상:바이올렛|사이즈:66 / 1개        라인어디션
6183981     여성의류상의    여성남방셔츠  7933941        색상:스카이블루/사이즈:Free         [오드]
6184005  남성일반스포츠의류  남성스포츠티셔츠  3185522               사이즈:100(L)   [아디다스(의류)]

        DVC_CTG_NM            ZON_NM       CITY_NM
6           mobile  Gyeongsangnam-do    Sacheon-si
51         desktop  Gyeongsangnam-do     Gimhae-si
61         desktop  Gyeongsangnam-do     Gimhae-si
62          mobile  Gyeongsangnam-do     Gimhae-si
98          mobile  Gyeongsangnam-do  Hapcheon-gun
...            ...               ...           ...
6183827     mobile  Gyeongsangnam-do     Gimhae-si
6183894     mobile  Gyeongsangnam-do  Geochang-gun
6183944     mobile  Gyeongsangnam-do     Haman-gun
6183981     mobile  Gyeongsangnam-do     Haman-gun
6184005    desktop  Gyeongsangnam-do  Tongyeong-si

[302693 rows x 12 columns]

In [69]:
cnt = {}

for data in gnam:
    try: cnt[data] +=1
    except: cnt[data] = 1

cntsortt = sorted(cnt.items(), key = lambda x:x[1], reverse=True)
print(cntsortt[:10])

[(380539, 2440), (753343, 529), (559754, 501), (247522, 419), (748308, 355), (1965, 312), (768597, 266), (755981, 250), (554713, 230), (706924, 185)]

In [72]:
data1 = regionData[regionData['PD_C'] == 380539 ]
data2 = regionData[regionData['PD_C'] == 753343 ]
data3 = regionData[regionData['PD_C'] == 559754 ]
data4 = regionData[regionData['PD_C'] == 247522 ]
data5 = regionData[regionData['PD_C'] == 748308 ]
data6 = regionData[regionData['PD_C'] == 1965 ]
data7 = regionData[regionData['PD_C'] == 768597]
data8 = regionData[regionData['PD_C'] ==755981]
data9 = regionData[regionData['PD_C'] == 554713 ]
data10 = regionData[regionData['PD_C'] == 706924 ]


data1 = data1[:1]
data2 = data2[:1]
data3 = data3[:1]
data4 = data4[:1]
data5 = data5[:1]
data6 = data6[:1]
data7 = data7[:1]
data8 = data8[:1]
data9 = data9[:1]
data10 = data10[:1]

In [73]:
rank = data1
rank = rank.append(data2)
rank = rank.append(data3)
rank = rank.append(data4)
rank = rank.append(data5)
rank = rank.append(data6)
rank = rank.append(data7)
rank = rank.append(data8)
rank = rank.append(data9)
rank = rank.append(data10)
rank

,Unnamed: 0,PD_C,PD_NM,CLAC1_NM,CLAC2_NM,CLAC3_NM,SESS_ID,PD_ADD_NM,PD_BRA_NM,DVC_CTG_NM,ZON_NM,CITY_NM
4289955,4289955,380539,여성 브이넥 반소매 티셔츠 TFMS1KOE65D0 - N00(화이트) / M,여성의류,여성의류상의,여성티셔츠/탑,7611385,색상:N00(화이트)|사이즈:S / 1개,타미힐피거여성,mobile,Gyeongsangnam-do,Jinju-si
347613,347613,753343,남성 드로즈 15종 택1 - 06_CCCDRM92WN / 105,속옷/양말/홈웨어,남성속옷,남성팬티,1215019,상품명:06)CDCDRM92NY/사이즈:100,[코데즈컴바인 이너웨어],desktop,Jeollanam-do,Yeosu-si
2258762,2258762,559754,여성 베이직 스트라이프 크루넥 티셔츠 TUNS1KOE23D0 - 멀티핑크(N29) / M,남성의류,남성의류상의,남성티셔츠,10822595,색상:라이트블루(N27)|사이즈:M / 1개,타미진,mobile,Gyeonggi-do,Yongin-si
775905,775905,247522,여성 슬림핏 플래그 피케 티셔츠 (TFMS1KTE60D0) - 그린(G30) / L...,여성의류,여성의류상의,여성티셔츠/탑,1569595,색상:핑크(R20)/사이즈:M(66),[타미힐피거여성],desktop,Jeollabuk-do,Gimje-si
2871969,2871969,748308,립스틱 - 온 홀드,화장품/뷰티케어,메이크업,립스틱/립라이너,8340830,색상:디바,[맥],desktop,Seoul,Seoul
3288506,3288506,1965,홍삼정 에브리타임(10mlx30포) / 롯데백화점 본점 출고 / 정관장,건강식품,홍삼/인삼가공식품,홍삼액,6195715,1개,정관장,mobile,Gyeonggi-do,Anyang
1492943,1492943,768597,패턴/솔리드 남성 드로즈 30종 택1 - 004)EHD5671 / 100,속옷/양말/홈웨어,남성속옷,남성팬티,8511021,상품명:002)EHD5669|사이즈:100 / 1개,엘르이너웨어,mobile,Seoul,Seoul
2515580,2515580,755981,홍삼정진(進) 에브리타임 10mx30포 + 쇼핑백 증정 - 홍삼정진에브리타임,건강식품,홍삼/인삼가공식품,홍삼/인삼혼합세트,906695,선택:홍삼정진에브리타임 / 1개,정관장.,mobile,Seoul,Seoul
3930148,3930148,554713,3D 지비츠 - 크록스악세사리 - 01.흰고래-꼬리,출산/육아용품,수유/이유용품,출산/신생아용품세트,10957894,선택:05.파랑상어-지느러미 / 1개,플레이비츠,mobile,Seoul,Seoul
616126,616126,706924,아몬드브리즈 오리지널 190ml 24팩 - 아몬드 브리즈 오리지널 190mlx24팩,음료,두유,일반두유,9826914,상품명:아몬드 브리즈 오리지널 190mlx24팩 / 1개,매일,mobile,Seoul,Seoul

## 대구

In [3]:
daegu_filter = regionData['ZON_NM']=='Daegu'
print(regionData[daegu_filter])

daegu_data = regionData[daegu_filter]
daegu = daegu_data['PD_C']

         Unnamed: 0    PD_C  \
3                 3   64382
20               20   58098
44               44  124084
58               58  209216
77               77  209216
...             ...     ...
6183908     6183908   31999
6183911     6183911   28292
6183925     6183925   62311
6184001     6184001  412759
6184009     6184009  400197

                                                     PD_NM   CLAC1_NM  \
3         언더아머 남성 UA HG 아머 모크 LS 1289559-001 - 블랙 / MD[95]      스포츠패션
20              V넥 고방 체크 롱 원피스 (K65-54615) - 스카이블루(SB) / F       여성의류
44                             여성백팩01H1280UBJ,UBN1FR - 그레이       패션잡화
58       코튼 혼방 폴로 피케 반팔 티셔츠( TBMS1KTS23A0-B30) - B30 / ...      유아동의류
77       코튼 혼방 폴로 피케 반팔 티셔츠( TBMS1KTS23A0-B30) - B30 / ...      유아동의류
...                                                    ...        ...
6183908                        남성 미디 삼각팬티 3매입(L2340) - 100  속옷/양말/홈웨어
6183911               레오파드 미니 스커트_[O1809SK047C] - 브라운 / 66       여성의류
6183925  멀티 키즈 얌얌 클래식 후디_PKOEAHD01C - 옐로우-PKOEAHD01CY4 ...      유아동의류
6184001   뉴에이스 스트라이프 베이직 카라셔츠 AE8S401 - AE8S401 네이비2 / 100      스포츠패션
6184009                  섀르반 올인원 수영복 (K14D5DM231) - BL/110      시즌스포츠

          CLAC2_NM       CLAC3_NM  SESS_ID                   PD_ADD_NM  \
3        남성일반스포츠의류       남성스포츠티셔츠  2330751       색상:블랙|사이즈:MD[95] / 1개
20          여성의류전신          여성원피스  2259589         색상:스카이블루|사이즈:F / 1개
44            여성가방           여성백팩  4307501                 색상:그레이 / 1개
58          남아의류상의        남아티셔츠/탑  6784361   색상:B30|직접입력2:12(150) / 1개
77          남아의류상의        남아티셔츠/탑  6992934   색상:B30|직접입력2:16(170) / 1개
...            ...            ...      ...                         ...
6183908       남성속옷           남성팬티  1619584                사이즈:100 / 1개
6183911     여성의류하의          여성스커트   724986          색상:브라운|사이즈:55 / 1개
6183925     여아의류상의  여아스웨트셔츠/후드/집업  2046833  색상:옐로우-PKOEAHD01CY4/사이즈:9T
6184001     남성골프의류        남성골프티셔츠  7339599       색상:AE8S401 블루/사이즈:105
6184009     수영/물놀이          아동수영복  5969955          색상/사이즈:PK/120 / 1개

          PD_BRA_NM DVC_CTG_NM ZON_NM CITY_NM
3         언더아머(스포츠)    desktop  Daegu   Daegu
20              오조크     mobile  Daegu   Daegu
44       피에르가르뎅_핸드백     mobile  Daegu   Daegu
58        타미힐피거 칠드런     mobile  Daegu   Daegu
77        타미힐피거 칠드런     mobile  Daegu   Daegu
...             ...        ...    ...     ...
6183908        비와이씨     mobile  Daegu   Daegu
6183911    올리비에스클로젯     mobile  Daegu   Daegu
6183925    [팬콧(키즈)]    desktop  Daegu   Daegu
6184001      [럭스골프]     mobile  Daegu   Daegu
6184009         섀르반     mobile  Daegu   Daegu

[265549 rows x 12 columns]

In [4]:
cnt = {}

for data in daegu:
    try: cnt[data] +=1
    except: cnt[data] = 1

cntsortt = sorted(cnt.items(), key = lambda x:x[1], reverse=True)
print(cntsortt[:10])

[(753343, 612), (748308, 313), (1965, 301), (755981, 237), (554713, 202), (768597, 200), (826313, 200), (405756, 190), (737743, 179), (706924, 170)]

In [5]:
data1 = regionData[regionData['PD_C'] == 753343 ]
data2 = regionData[regionData['PD_C'] == 748308 ]
data3 = regionData[regionData['PD_C'] == 1965 ]
data4 = regionData[regionData['PD_C'] == 755981 ]
data5 = regionData[regionData['PD_C'] == 554713 ]
data6 = regionData[regionData['PD_C'] == 768597 ]
data7 = regionData[regionData['PD_C'] == 826313]
data8 = regionData[regionData['PD_C'] ==405756]
data9 = regionData[regionData['PD_C'] == 737743]
data10 = regionData[regionData['PD_C'] == 706924 ]


data1 = data1[:1]
data2 = data2[:1]
data3 = data3[:1]
data4 = data4[:1]
data5 = data5[:1]
data6 = data6[:1]
data7 = data7[:1]
data8 = data8[:1]
data9 = data9[:1]
data10 = data10[:1]

In [6]:
rank = data1
rank = rank.append(data2)
rank = rank.append(data3)
rank = rank.append(data4)
rank = rank.append(data5)
rank = rank.append(data6)
rank = rank.append(data7)
rank = rank.append(data8)
rank = rank.append(data9)
rank = rank.append(data10)
rank

,Unnamed: 0,PD_C,PD_NM,CLAC1_NM,CLAC2_NM,CLAC3_NM,SESS_ID,PD_ADD_NM,PD_BRA_NM,DVC_CTG_NM,ZON_NM,CITY_NM
347613,347613,753343,남성 드로즈 15종 택1 - 06_CCCDRM92WN / 105,속옷/양말/홈웨어,남성속옷,남성팬티,1215019,상품명:06)CDCDRM92NY/사이즈:100,[코데즈컴바인 이너웨어],desktop,Jeollanam-do,Yeosu-si
2871969,2871969,748308,립스틱 - 온 홀드,화장품/뷰티케어,메이크업,립스틱/립라이너,8340830,색상:디바,[맥],desktop,Seoul,Seoul
3288506,3288506,1965,홍삼정 에브리타임(10mlx30포) / 롯데백화점 본점 출고 / 정관장,건강식품,홍삼/인삼가공식품,홍삼액,6195715,1개,정관장,mobile,Gyeonggi-do,Anyang
2515580,2515580,755981,홍삼정진(進) 에브리타임 10mx30포 + 쇼핑백 증정 - 홍삼정진에브리타임,건강식품,홍삼/인삼가공식품,홍삼/인삼혼합세트,906695,선택:홍삼정진에브리타임 / 1개,정관장.,mobile,Seoul,Seoul
3930148,3930148,554713,3D 지비츠 - 크록스악세사리 - 01.흰고래-꼬리,출산/육아용품,수유/이유용품,출산/신생아용품세트,10957894,선택:05.파랑상어-지느러미 / 1개,플레이비츠,mobile,Seoul,Seoul
1492943,1492943,768597,패턴/솔리드 남성 드로즈 30종 택1 - 004)EHD5671 / 100,속옷/양말/홈웨어,남성속옷,남성팬티,8511021,상품명:002)EHD5669|사이즈:100 / 1개,엘르이너웨어,mobile,Seoul,Seoul
2115835,2115835,826313,풀무원 생수 2L x 6페트,음료,생수,생수,5101523,1개,웅진식품,mobile,Gwangju,Gwangju
4262827,4262827,405756,[B]자음 기초2종 기획세트 - 셋트,화장품/뷰티케어,스킨케어,스킨케어세트,9588929,옵션:세트 / 3개,설화수,desktop,Gangwon-do,Gangneung-si
2918704,2918704,737743,[리필] 르 쿠션 엉크르 드 뽀 SPF23 PA++ 14g - 40,화장품/뷰티케어,메이크업,BB/파운데이션/컴팩트류,9706493,색상:10 / 1개,입생로랑,mobile,Busan,Busan
616126,616126,706924,아몬드브리즈 오리지널 190ml 24팩 - 아몬드 브리즈 오리지널 190mlx24팩,음료,두유,일반두유,9826914,상품명:아몬드 브리즈 오리지널 190mlx24팩 / 1개,매일,mobile,Seoul,Seoul

## 인천

In [7]:
incheon_filter = regionData['ZON_NM']=='Incheon'
print(regionData[incheon_filter])

incheon_data = regionData[incheon_filter]
incheon = incheon_data['PD_C']

         Unnamed: 0    PD_C  \
56               56  209216
57               57  209216
65               65  209216
69               69  209216
70               70  209216
...             ...     ...
6183813     6183813     242
6183831     6183831    5827
6183839     6183839    5827
6183898     6183898     859
6183926     6183926   62311

                                                     PD_NM   CLAC1_NM  \
56       코튼 혼방 폴로 피케 반팔 티셔츠( TBMS1KTS23A0-B30) - B30 / ...      유아동의류
57       코튼 혼방 폴로 피케 반팔 티셔츠( TBMS1KTS23A0-B30) - B30 / ...      유아동의류
65       코튼 혼방 폴로 피케 반팔 티셔츠( TBMS1KTS23A0-B30) - B30 / ...      유아동의류
69       코튼 혼방 폴로 피케 반팔 티셔츠( TBMS1KTS23A0-B30) - B30 / ...      유아동의류
70       코튼 혼방 폴로 피케 반팔 티셔츠( TBMS1KTS23A0-B30) - B30 / ...      유아동의류
...                                                    ...        ...
6183813                   캐릭터 양말 20종 택1 - 11.(여)버블베이비 / 블루  속옷/양말/홈웨어
6183831                            롯데 아이시스 8.0 2L (1묶음 6개)         음료
6183839                            롯데 아이시스 8.0 2L (1묶음 6개)         음료
6183898               키친아트 프레시오(PRECIO) 통오중(5PLY) 미니냄비14CM    식기/조리기구
6183926  멀티 키즈 얌얌 클래식 후디_PKOEAHD01C - 옐로우-PKOEAHD01CY4 ...      유아동의류

        CLAC2_NM       CLAC3_NM  SESS_ID                   PD_ADD_NM  \
56        남아의류상의        남아티셔츠/탑  6734643   색상:B30|직접입력2:07(125) / 1개
57        남아의류상의        남아티셔츠/탑  7031431   색상:B30|직접입력2:06(120) / 1개
65        남아의류상의        남아티셔츠/탑  7031431   색상:B30|직접입력2:08(130) / 1개
69        남아의류상의        남아티셔츠/탑  4492921   색상:B30|직접입력2:08(130) / 1개
70        남아의류상의        남아티셔츠/탑  7031431   색상:B30|직접입력2:10(140) / 1개
...          ...            ...      ...                         ...
6183813    여성양말류         여성일반양말  7625041  상품명:11.(여)버블베이비|색상:블루 / 1개
6183831       생수             생수  3538277                          6개
6183839       생수             생수  3270038                          2개
6183898     조리기구             냄비  3538529                          1개
6183926   여아의류상의  여아스웨트셔츠/후드/집업  2046833  색상:옐로우-PKOEAHD01CY4/사이즈:9T

         PD_BRA_NM DVC_CTG_NM   ZON_NM  CITY_NM
56       타미힐피거 칠드런     mobile  Incheon  Incheon
57       타미힐피거 칠드런     mobile  Incheon  Incheon
65       타미힐피거 칠드런     mobile  Incheon  Incheon
69       타미힐피거 칠드런     mobile  Incheon  Incheon
70       타미힐피거 칠드런     mobile  Incheon  Incheon
...            ...        ...      ...      ...
6183813       제이핑크     mobile  Incheon  Incheon
6183831        쥬맥스     mobile  Incheon  Incheon
6183839        쥬맥스    desktop  Incheon  Incheon
6183898       키친아트     mobile  Incheon  Incheon
6183926   [팬콧(키즈)]    desktop  Incheon  Incheon

[229115 rows x 12 columns]

In [8]:
cnt = {}

for data in incheon:
    try: cnt[data] +=1
    except: cnt[data] = 1

cntsortt = sorted(cnt.items(), key = lambda x:x[1], reverse=True)
print(cntsortt[:10])

[(753343, 499), (843603, 290), (748308, 251), (1965, 248), (755981, 194), (826313, 193), (768597, 182), (741838, 175), (839528, 171), (718416, 168)]

In [10]:
data1 = regionData[regionData['PD_C'] == 753343 ]
data2 = regionData[regionData['PD_C'] == 843603 ]
data3 = regionData[regionData['PD_C'] == 748308 ]
data4 = regionData[regionData['PD_C'] == 1965 ]
data5 = regionData[regionData['PD_C'] == 755981 ]
data6 = regionData[regionData['PD_C'] == 826313 ]
data7 = regionData[regionData['PD_C'] == 768597 ]
data8 = regionData[regionData['PD_C'] ==741838 ]
data9 = regionData[regionData['PD_C'] == 839528 ]
data10 = regionData[regionData['PD_C'] == 7718416 ]


data1 = data1[:1]
data2 = data2[:1]
data3 = data3[:1]
data4 = data4[:1]
data5 = data5[:1]
data6 = data6[:1]
data7 = data7[:1]
data8 = data8[:1]
data9 = data9[:1]
data10 = data10[:1]

In [11]:
rank = data1
rank = rank.append(data2)
rank = rank.append(data3)
rank = rank.append(data4)
rank = rank.append(data5)
rank = rank.append(data6)
rank = rank.append(data7)
rank = rank.append(data8)
rank = rank.append(data9)
rank = rank.append(data10)
rank

,Unnamed: 0,PD_C,PD_NM,CLAC1_NM,CLAC2_NM,CLAC3_NM,SESS_ID,PD_ADD_NM,PD_BRA_NM,DVC_CTG_NM,ZON_NM,CITY_NM
347613,347613,753343,남성 드로즈 15종 택1 - 06_CCCDRM92WN / 105,속옷/양말/홈웨어,남성속옷,남성팬티,1215019,상품명:06)CDCDRM92NY/사이즈:100,[코데즈컴바인 이너웨어],desktop,Jeollanam-do,Yeosu-si
912772,912772,843603,도담이 100매 10팩 캡형 도톰한 물티슈 평량 50g - 100매 10팩 캡형,출산/육아용품,유아위생용품,유아용물티슈,8630122,모델명:100매 10팩 캡형 / 2개,도담이,mobile,Seoul,Seoul
2871969,2871969,748308,립스틱 - 온 홀드,화장품/뷰티케어,메이크업,립스틱/립라이너,8340830,색상:디바,[맥],desktop,Seoul,Seoul
3288506,3288506,1965,홍삼정 에브리타임(10mlx30포) / 롯데백화점 본점 출고 / 정관장,건강식품,홍삼/인삼가공식품,홍삼액,6195715,1개,정관장,mobile,Gyeonggi-do,Anyang
2515580,2515580,755981,홍삼정진(進) 에브리타임 10mx30포 + 쇼핑백 증정 - 홍삼정진에브리타임,건강식품,홍삼/인삼가공식품,홍삼/인삼혼합세트,906695,선택:홍삼정진에브리타임 / 1개,정관장.,mobile,Seoul,Seoul
2115835,2115835,826313,풀무원 생수 2L x 6페트,음료,생수,생수,5101523,1개,웅진식품,mobile,Gwangju,Gwangju
1492943,1492943,768597,패턴/솔리드 남성 드로즈 30종 택1 - 004)EHD5671 / 100,속옷/양말/홈웨어,남성속옷,남성팬티,8511021,상품명:002)EHD5669|사이즈:100 / 1개,엘르이너웨어,mobile,Seoul,Seoul
1356719,1356719,741838,치크 팝 3.5g (NEW 4가지 컬러 추가 출시) - 13 로지 팝,화장품/뷰티케어,메이크업,블러셔/쉐이딩/하이라이터,3113312,색상:18 핑크 허니 팝 / 1개,크리니크,mobile,Seoul,Seoul
3691549,3691549,839528,[당일배송] 2018 NEW UV플랩캡/캠핑햇 13종 택 1 - 10.캠핑햇_GRE...,패션잡화,모자,아동모,10710904,디자인:05.플랩캡_IVORY/사이즈:L,[베이비반즈],desktop,Seoul,Seoul

### 한번에 많이 사는 제품군 분석해보기

In [16]:
prod = pd.read_csv('01.Pruduct.csv')

C:\Users\User\anaconda3.7\envs\chaelin_virtenv\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (7) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [52]:
cnt = prod['PD_BUY_CT'] == 300
prod[cnt]

,CLNT_ID,SESS_ID,HITS_SEQ,PD_C,PD_ADD_NM,PD_BRA_NM,PD_BUY_AM,PD_BUY_CT
86090,6115621,9383518,50,771600,색상:레오파드/사이즈:66,[쿠기],"1,000",300

In [22]:
sess = pd.read_csv('05.Session.csv')

In [25]:
ssun = pd.merge(sess, prod, left_on='SESS_ID', right_on = 'SESS_ID', how='left')

In [80]:
test = ssun['PD_C'] == 247522
ssun[test][31:40]

,CLNT_ID_x,SESS_ID,SESS_SEQ,SESS_DT,TOT_PAG_VIEW_CT,TOT_SESS_HR_V,DVC_CTG_NM,ZON_NM,CITY_NM,CLNT_ID_y,HITS_SEQ,PD_C,PD_ADD_NM,PD_BRA_NM,PD_BUY_AM,PD_BUY_CT
3117943,2776619,4001124,3,20180725,37.0,"1,168",desktop,Gangwon-do,Wonju-si,2776619,12,247522,색상:핑크(R20)/사이즈:L(77),[타미힐피거여성],"73,500",1
3123240,2842389,1908376,45,20180829,23.0,"1,403",desktop,Seoul,Seoul,2842389,25,247522,색상:핑크(R20)/사이즈:M(66),[타미힐피거여성],"73,500",1
3354790,4615040,7108349,400,20180604,233.0,"8,434",mobile,Seoul,Seoul,4615040,35,247522,색상:블루(B40)|사이즈:S(55) / 1개,타미힐피거여성,"73,500",1
3807818,1708859,7424479,2,20180529,136.0,"5,043",desktop,Incheon,Incheon,1708859,152,247522,색상:블루(B40)/사이즈:L(77),[타미힐피거여성],"73,500",1
3976113,4736937,2429909,1330,20180820,247.0,"2,875",mobile,Gyeongsangnam-do,Jinju-si,4736937,54,247522,색상:그린(G30)|사이즈:L(77) / 1개,타미힐피거여성,"73,500",1
3976114,4736937,2429909,1330,20180820,247.0,"2,875",mobile,Gyeongsangnam-do,Jinju-si,4736937,197,247522,색상:핑크(R20)|사이즈:L(77) / 1개,타미힐피거여성,"73,500",1
3976115,4736937,2429909,1330,20180820,247.0,"2,875",mobile,Gyeongsangnam-do,Jinju-si,4736937,66,247522,색상:레드(R30)|사이즈:XS(44) / 1개,타미힐피거여성,"73,500",1
3976116,4736937,2429909,1330,20180820,247.0,"2,875",mobile,Gyeongsangnam-do,Jinju-si,4736937,78,247522,색상:레드(R30)|사이즈:S(55) / 1개,타미힐피거여성,"73,500",1
3976117,4736937,2429909,1330,20180820,247.0,"2,875",mobile,Gyeongsangnam-do,Jinju-si,4736937,208,247522,색상:그린(G30)|사이즈:XS(44) / 1개,타미힐피거여성,"73,500",1

Empty DataFrame
Columns: [CLNT_ID_x, SESS_ID, SESS_SEQ, SESS_DT, TOT_PAG_VIEW_CT, TOT_SESS_HR_V, DVC_CTG_NM, ZON_NM, CITY_NM, CLNT_ID_y, HITS_SEQ, PD_C, PD_ADD_NM, PD_BRA_NM, PD_BUY_AM, PD_BUY_CT]
Index: []